#!/bin/bash

if [ ! -f ./flradio.bin ]; then
    SCRIPT_DIR=$(readlink -f ${0%/*})
    if [ -d $SCRIPT_DIR/../share/flradio ]; then
        cd $SCRIPT_DIR/../share/flradio
    else
        cd $SCRIPT_DIR/share/flradio
    fi
fi
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$PWD"
./flradio.bin
