#include "stations.h"

void Stations::add_serbia(Fl_Browser *r)
{
r->add("AS FM|https://mastermedia.shoutca.st/proxy/radioasfm?mp=/stream");
r->add("Active Radio Bečej|http://active96-naxinacional.streaming.rs:8555/");
r->add("Ami Naxi Radio Kikinda|http://185.119.88.88:8005/");
r->add("Antena Krusevac|http://antenaradio.org:4560/;stream.nsv");
r->add("Antena Radio Bor|http://37.120.184.200:8018/");
r->add("Antena Radio Kruševac|http://antenaradio.org:4560/listen.pls");
r->add("BANKER|http://banker96-naxinacional.streaming.rs:8540/");
r->add("BFM Radio Beograd|http://dione.shoutca.st:8359/;");
r->add("Batiskaf Radio|https://srv.mediastriming.com/8008/stream");
r->add("Bela Crkva|http://belacrkva32.streaming.rs:8140/listen.pls");
r->add("Belami radio |http://92.60.230.200:5040/listen.pls");
r->add("Beseda|http://92.61.114.191:9180/stream");
r->add("Boemi Radio|http://79.142.73.156:8570/;*.mp3");
r->add("Bravo FM|http://streaming.orion.rs:8030/");
r->add("Bum Bum Radio|http://bumbum-stream.netlogic.rs:8000/listen.pls");
r->add("Bum radio|http://217.24.17.31:8102/;stream.nsv");
r->add("Cool Radio|http://176.9.30.66/cool64");
r->add("Dasko i Mladja|http://172.105.250.193:8000/stream");
r->add("Deluxe Radio|http://cmr-hosting.com:8408/;*.mp3");
r->add("Egata Radio|http://stream.zeno.fm/kcn3b5gfuhruv");
r->add("Fan Radio Bajina Basta|http://stream.fanradio.info:9000/;stream.nsv");
r->add("Focus Radio|https://streamer.radio.co/s34d2c17d8/listen");
r->add("Folk Radio Beograd|http://usa6.fastcast4u.com:5010/stream");
r->add("Fox Radio|http://stream.foxradio.rs:8545/;stream.mp3");
r->add("HIT FM Acoustic|http://streaming.hitfm.rs/acoustic.mp3");
r->add("Hit FM Radio Beograd|http://streaming.hitfm.rs:8000/hit");
r->add("Karolina|http://streaming.karolina.rs:8000/karolina");
r->add("Kragujevac Plaza Radio|http://109.206.96.18:8020/;stream.nsv");
r->add("Krajiski Radio|http://falcon.shoutca.st:8531/;");
r->add("Kruna|http://87.116.152.185:9090/;stream.nsv");
r->add("Lotel2|https://s1.skeletor.rs/lotel");
r->add("Moj radio|http://eu4.fastcast4u.com:5692/");
r->add("Morava ETNO Radio Jagodina|https://e3.radiomorava.rs/radio/8050/etno.mp3");
r->add("Morava KOLO Radio Jagodina|https://e3.radiomorava.rs/radio/8040/kolo.mp3");
r->add("Morava POP ROK Radio Jagodina|https://e3.radiomorava.rs/radio/8060/poprok.mp3");
r->add("Morava TOP 50 Radio Jagodina|https://e3.radiomorava.rs/radio/8070/top50.mp3");
r->add("Morava VIC Radio Jagodina|https://e3.radiomorava.rs/radio/8020/vic.mp3");
r->add("Muzički Radio Fan|http://stream.fanradio.info:9000/listen.pls");
r->add("Mária Rádió Szerbia|http://dreamsiteradiocp.com:8014/;");
r->add("Naxi - hype|https://naxidigital-hype128ssl.streaming.rs:8272/;stream.nsv");
r->add("Naxi 80-e Radio|https://naxidigital-80s128ssl.streaming.rs:8042/;");
r->add("Naxi 90s|https://naxidigital-90s128ssl.streaming.rs:8282/;stream.nsv");
r->add("Naxi Adore|https://naxidigital-adore128ssl.streaming.rs:8332/;stream.nsv");
r->add("Naxi Adore|https://naxidigital-adore128ssl.streaming.rs:8332/;stream.nsv");
r->add("Naxi Blues|https://naxidigital-blues128ssl.streaming.rs:8312/;stream.nsv");
r->add("Naxi Boem Radio|https://naxidigital-boem128ssl.streaming.rs:8162/;");
r->add("Naxi Cafe Radio|http://naxidigital-128.kbcnet.rs:8020/");
r->add("Naxi Cafe Radio|https://naxidigital-cafe128ssl.streaming.rs:8022/;");
r->add("Naxi Chillwave|https://naxidigital-chillwave128ssl.streaming.rs:8322/;stream.nsv");
r->add("Naxi Classic Radio|https://naxidigital-classic128ssl.streaming.rs:8032/;");
r->add("Naxi Clubbing Radio |https://naxidigital-clubbing128ssl.streaming.rs:8092/;");
r->add("Naxi Dance Radio|https://naxidigital-dance128ssl.streaming.rs:8112/;");
r->add("Naxi Evergreen Radio|http://naxidigital-128.kbcnet.rs:8010/");
r->add("Naxi Evergreen Radio|https://naxidigital-evergreen128ssl.streaming.rs:8012/;");
r->add("Naxi ExYu Radio HTTP|http://naxidigital-exyu48.streaming.rs:8245/");
r->add("Naxi ExYu Radio|https://naxidigital-exyu128ssl.streaming.rs:8242/;stream.nsv");
r->add("Naxi Fitness|https://naxidigital-fitness128ssl.streaming.rs:8292/;stream.nsv");
r->add("Naxi Fresh Radio|https://naxidigital-fresh128ssl.streaming.rs:8212/;stream.nsv");
r->add("Naxi Gold Radio|https://naxidigital-gold128ssl.streaming.rs:8062/;stream.nsv");
r->add("Naxi House Radio|https://naxidigital-house128ssl.streaming.rs:8002/;");
r->add("Naxi Hype Radio|https://naxidigital-hype128ssl.streaming.rs:8272/;");
r->add("Naxi Jazz Radio|https://naxidigital-jazz128ssl.streaming.rs:8172/;stream.nsv");
r->add("Naxi Kids Radio|https://naxidigital-kids128ssl.streaming.rs:8052/;");
r->add("Naxi Kids SERBIA |http://naxidigital-kids128.streaming.rs:8050/");
r->add("Naxi Latino Radio|https://naxidigital-latino128ssl.streaming.rs:8232/;stream.nsv");
r->add("Naxi Lounge Radio|https://naxidigital-lounge128ssl.streaming.rs:8252/;stream.nsv");
r->add("Naxi Love Radio|https://naxidigital-love128ssl.streaming.rs:8102/;");
r->add("Naxi Mix Radio|https://naxidigital-mix128ssl.streaming.rs:8222/;stream.nsv");
r->add("Naxi R'n'B Radio|https://naxidigital-rnb128ssl.streaming.rs:8122/;stream.nsv");
r->add("Naxi Radio - Lounge|http://naxidigital-lounge128.streaming.rs:8250/listen.pls");
r->add("Naxi Radio Chillwave|http://naxidigital-chillwave128.streaming.rs:8320/listen.pls");
r->add("Naxi Radio|http://naxi128.streaming.rs:9150/");
r->add("Naxi Radio|http://naxi48.streaming.rs:9180/listen.pls");
r->add("Naxi Rock radio|https://naxidigital-rock128ssl.streaming.rs:8182/;");
r->add("No Limit Radio|http://webradio.sksyu.net:8000/nolimithq.ogg");
r->add("OK Radio Prelo|http://live.okplus.rs:8050/;*.mp3");
r->add("OK radio plus|http://live.okplus.rs:8000/;stream.nsv");
r->add("OK radio|https://sslstream.okradio.net/;?type=http&nocache=8804");
r->add("Ob-neob radio |https://s5.voscast.com:10151/stream?fbclid=IwAR1UV8jq3TBf4TS2YoPkrOo9_EnqAWRm8yU_HYbLj22k4DQM4mgNjkKClHE");
r->add("ObNeob|https://s5.voscast.com:10151/stream");
r->add("ObNeob|https://s5.voscast.com:10151/stream");
r->add("Obavezno Neobavezno sa Brakusom i Banjcem|https://s5.voscast.com:10151/stream");
r->add("Omnibus Youth Radio|http://46.22.145.218:8000/stream.mp3");
r->add("Pannon Rádió|http://breddstream.unrealhosting.hu:4120/;");
r->add("Pink Radio|http://edge1.pink.rs:1935/radiopinkfta/pink61.smil/playlist.m3u8");
r->add("Pink radio|http://pink.exyuserver.com/;stream.mp3");
r->add("Play Radio Party|https://stream.playradio.rs:8443/party.mp3");
r->add("Play Radio Rock|https://stream.playradio.rs:8443/rock.mp3");
r->add("Play Radio Serbia|https://stream.playradio.rs:8443/play.mp3");
r->add("Play Radio Soft 2|https://stream.playradio.rs:8443/soft.mp3");
r->add("Play Radio Urban|https://stream.playradio.rs:8443/urban.mp3");
r->add("Play|http://stream.playradio.rs:8001/play.aac.m3u");
r->add("Prvi radio Novi Sad|https://mastermedia.shoutca.st/proxy/prviradions?mp=/stream");
r->add("RADIO MARIA SERBIA HUNG|http://dreamsiteradiocp.com:8014/stream");
r->add("RADIO MARIA SERBIA HUNG|http://dreamsiteradiocp2.com:8062/stream");
r->add("RADIO MARIA SERBIA|http://dreamsiteradiocp.com:8012/stream");
r->add("RADIO S KIDS|https://5bc45691ca49f.streamlock.net/asmedia/radio_s_kids/playlist.m3u8");
r->add("RADIO.D59B|http://stream.radiojar.com/gn6dqzhf9mzuv.m3u");
r->add("RSG Party time|https://stream.rsg.rs/partytime/");
r->add("RSG Radio Stari Grad|https://stream.rsg.rs/live/");
r->add("RSG Relax|https://stream.rsg.rs/relax/");
r->add("RSG Top 44|https://stream.rsg.rs/top44/");
r->add("Radio 016 Leskovac|http://radiostreaming.ninet.rs:8400/stream/1/");
r->add("Radio 021|https://radio.dukahosting.com/8006/stream");
r->add("Radio 3 LIVE|https://radio3-64ssl.streaming.rs:9212/;stream.nsv");
r->add("Radio 34|http://stream.radio34.rs:8889/;*.mp3");
r->add("Radio 3|http://radio3-128.streaming.rs:9200/");
r->add("Radio 4P Narodna Muzika|http://server4p.com:8002/stream");
r->add("Radio 4P Zabavna Muzika|http://server4p.com/8012/stream");
r->add("Radio Ada 107,7|http://94.130.196.243:9010/stream");
r->add("Radio Aparat|http://ca3.rcast.net:8060/;stream.mp3;");
r->add("Radio Apatin|http://apatin96-naxinacional.streaming.rs:8500/listen.pls");
r->add("Radio B92|http://stream.b92.net:7999/radio-b92.mp3");
r->add("Radio BG1|https://rtsradio-live.morescreens.com/RTS_2_001/playlist.m3u8");
r->add("Radio Belle Amie Niš|http://92.60.230.200:5040/");
r->add("Radio Beograd 1|https://rtsradio-live.morescreens.com/RTS_2_001/audio/chunklist.m3u8");
r->add("Radio Beograd 2 link 2|https://rtsradio-live.morescreens.com/RTS_2_002/playlist.m3u8");
r->add("Radio Beograd 202|https://rtsradio-live.morescreens.com/RTS_2_004/playlist.m3u8");
r->add("Radio Beograd 2|http://138.201.33.203:8000/rts_2");
r->add("Radio Beograd|https://rtsradio-live.morescreens.com/RTS_2_001/audio/chunklist.m3u8");
r->add("Radio Blue Sky|http://82.114.72.2:8098/;stream.nsv");
r->add("Radio Boom93|http://159.69.105.22:9974/;stream.nsv");
r->add("Radio Bravo Kragujevac|http://streaming.orion.rs:8030/;stream.nsv");
r->add("Radio Bubamara|http://92.60.230.200:5010/;*.mp3");
r->add("Radio Buca|http://live.bucaradio.com:8080/listen.pls");
r->add("Radio Cer|http://stream1.contrateam.com:8040/listen.pls");
r->add("Radio D Lucani|http://213.239.205.210:6010/;stream.nsv");
r->add("Radio DAK|http://85.25.73.243:10150/listen.pls");
r->add("Radio Delta Novi Sad|https://radio.dukahosting.com:7015/stream?type=http&nocache=39");
r->add("Radio Delta|http://centova.dukahosting.com:2199/tunein/delta.pls");
r->add("Radio Desetka|http://pink.exyuserver.com/;*.mp3");
r->add("Radio D|http://213.239.205.210:6010/listen.pls");
r->add("Radio Džuboks |http://176.9.59.144:8090/dzuboks");
r->add("Radio Fantasy Vrbas|http://109.206.96.34:8575/;stream.nsv");
r->add("Radio Fruska Gora|https://stream.iradio.pro/proxy/radiofruskagora?mp=/stream");
r->add("Radio Glas Nade|http://109.235.71.229:8000/rgn1");
r->add("Radio Gold Braničevo|http://213.239.205.210:8018/listen.pls");
r->add("Radio Gong|http://stream1.contrateam.com:8044/;stream.nsv");
r->add("Radio IN Beograd|https://radio3-64ssl.streaming.rs:9212/;*.mp3");
r->add("Radio Javor Ivanjica|http://javor.streaming.rs:9320/;");
r->add("Radio Javor|http://javor.streaming.rs:9320/");
r->add("Radio K4|http://fm.radiokfor.com:8090/;stream.nsv");
r->add("Radio K4|http://fm.radiokfor.com:8090/listen.pls");
r->add("Radio Karolina - Classic hits 80′ 90′|http://streaming.karolina.rs/classics.mp3");
r->add("Radio Klik FM Zrenjanin|http://klikfm1.yunethosting.net:8000/stream");
r->add("Radio Koliba|http://radiokoliba.com:19334/stream");
r->add("Radio Kosava 1|https://main.radiokosava.rs/;stream.mp3");
r->add("Radio Kosava 2|https://kosava2.radiokosava.rs/;stream.mp3");
r->add("Radio Kosava Classic|https://klasik.radiokosava.rs/;stream.mp3");
r->add("Radio Kosava Folk 1|https://folk1.radiokosava.rs/;stream.mp3");
r->add("Radio Kosava Folk 2|https://folk2.radiokosava.rs/;stream.mp3");
r->add("Radio Kosava Folk 3|https://folk3.radiokosava.rs/;stream.mp3");
r->add("Radio Kosava Freedom|https://freedom.radiokosava.rs/;stream.mp3");
r->add("Radio Kosava Info|https://info.radiokosava.rs/;stream.mp3");
r->add("Radio Kosava Jazz|https://jazz.radiokosava.rs/;stream.mp3");
r->add("Radio Kosava Kids|https://kids.radiokosava.rs/;stream.mp3");
r->add("Radio Kosava Koncert 1|https://koncert1.radiokosava.rs/;stream.mp3");
r->add("Radio Kosava Koncert 2|https://koncert2.radiokosava.rs/;stream.mp3");
r->add("Radio Kosava Latino|https://latino.radiokosava.rs/;stream.mp3");
r->add("Radio Kosava Love 1|https://love.radiokosava.rs/;stream.mp3");
r->add("Radio Kosava Love 2|https://love2.radiokosava.rs/;stream.mp3");
r->add("Radio Kosava Rap|https://rap.radiokosava.rs/;stream.mp3");
r->add("Radio Kosava Rock|https://rock.radiokosava.rs/;stream.mp3");
r->add("Radio Kulska Komuna|http://as.q-media.rs:8000/mp3");
r->add("Radio Levač|http://213.239.205.210:8046/");
r->add("Radio Ljubav|http://ljubav.streaming.rs:9340/listen.pls");
r->add("Radio Lola - Domaca|https://streaming.tdiradio.com/radiolola.mp3");
r->add("Radio Mackica - Narodna Muzika|http://cast2.name.ba:8153/;stream.nsv");
r->add("Radio Mackica - Zabavna Muzika|http://cast2.name.ba:8157/;stream.nsv");
r->add("Radio Magnum|http://magnum.web-srbija.net:8121/;stream.nsv");
r->add("Radio Mačkica|http://cast2.name.ba:8153/;*.mp3");
r->add("Radio Morava|https://e3.radiomorava.rs/radio/8000/radiomorava128.mp3");
r->add("Radio Nostalgija AAC|http://nostalgie48.streaming.rs:9270/listen.pls");
r->add("Radio Nostalgija|http://nostalgie128.streaming.rs:9250/");
r->add("Radio Novi Grad|http://89.36.216.228:8585/;listen.pls");
r->add("Radio Novi Sad 1|http://79.101.121.123:1935/rns1/prviprogram/livestream/playlist.m3u8");
r->add("Radio Novi Sad 2 - Újvidéki Rádió|http://79.101.121.123:1935/rns2/drugiprogram/livestream/playlist.m3u8");
r->add("Radio Novi Sad 3|http://79.101.121.123:1935/rns3/treciprogram/livestream/playlist.m3u8");
r->add("Radio Novosti|http://www.radionovosti.rs:443/radionovosti56s.mp3.m3u");
r->add("Radio Patrola 021|https://srv.mediastriming.com/8444/stream");
r->add("Radio Pingvin|http://uzivo4.radiopingvin.com:8187/domaci1");
r->add("Radio Podrinje Loznica|http://s1.skeletor.rs:8000/podrinje");
r->add("Radio Puls Grocka|http://176.9.59.144:8090/puls");
r->add("Radio Razbibriga|http://213.239.205.210:8001/stream");
r->add("Radio Rodna Gruda|http://live.radiorodnagruda.net:9203/;stream.nsv");
r->add("Radio S Cafe|https://53be5ef2d13aa.streamlock.net/asmedia/radio_s_cafe/playlist.m3u8");
r->add("Radio S Dance|https://53a7ed211fc32.streamlock.net/asmedia/radio_s_energy/playlist.m3u8");
r->add("Radio S EX YU|https://53a7ed211fc32.streamlock.net/asmedia/radio_s_ex_yu/playlist.m3u8");
r->add("Radio S Easy|https://stream.radios.rs:9044/stream");
r->add("Radio S Folk Stars|https://53a7ed211fc32.streamlock.net/asmedia/radio_s_lounge/playlist.m3u8");
r->add("Radio S Južni|https://53a7ed211fc32.streamlock.net/asmedia/radio_s_juzni/playlist.m3u8");
r->add("Radio S Kids|https://53be5ef2d13aa.streamlock.net/asmedia/radio_s_kids/playlist.m3u8");
r->add("Radio S Narodni|https://stream.radios.rs:9016/;*.mp3");
r->add("Radio S POP&ROCK|https://53be5ef2d13aa.streamlock.net/asmedia/radio_s_pop_80_90/playlist.m3u8");
r->add("Radio S Rock|https://5bc45691ca49f.streamlock.net/asmedia/radio_s_rock/playlist.m3u8");
r->add("Radio S Trap&Rap|https://53a7ed211fc32.streamlock.net/asmedia/radio_s_mchits/playlist.m3u8");
r->add("Radio S Xtra|https://53a7ed211fc32.streamlock.net/asmedia/radio_s_love/playlist.m3u8");
r->add("Radio S1|http://edge-rs-01.maksnet.tv/asmedia/radios/chunklist_w2049618642.m3u8");
r->add("Radio S2|https://53be5ef2d13aa.streamlock.net/asmedia/index/playlist.m3u8");
r->add("Radio S3 Juzni|http://53a7ed211fc32.streamlock.net/asmedia/radio_s_juzni/chunklist_w317033927.m3u8?nocache=286704");
r->add("Radio S3 Južni|https://stream.radios.rs:9038/;*.mp3");
r->add("Radio S3|http://edge-rs-01.maksnet.tv/asmedia/pingvin/chunklist_w12686921.m3u8");
r->add("Radio S3|https://53be5ef2d13aa.streamlock.net/asmedia/pingvin/playlist.m3u8");
r->add("Radio S4|https://53a7ed211fc32.streamlock.net/asmedia/gradski/playlist.m3u8");
r->add("Radio S4|https://53be5ef2d13aa.streamlock.net/asmedia/gradski/playlist.m3u8");
r->add("Radio San Loznica|https://s1.skeletor.rs/san");
r->add("Radio Skay|http://radioskay.com/download/playlist.pls");
r->add("Radio Slavoslovlje|http://170.249.196.82:8000/;stream.nsv");
r->add("Radio Sljivovica|http://stream.iradio.pro:8114/;stream.nsv");
r->add("Radio Slobodna Evropa|http://rfe05.akacast.akamaistream.net/7/510/437763/v1/ibb.akacast.akamaistream.net/rfe05?download=1");
r->add("Radio Slovo Ljubve|http://160.153.245.85:8000/stream/1/;*.mp3");
r->add("Radio Song Niš|http://stream.zeno.fm/wn6rxh42czzuv");
r->add("Radio Stari Grad|http://stream.rsg.rs:8043/;stream.nsv");
r->add("Radio Strela (90.7 FM - Veliki Popovic-Despotovac)|http://176.9.59.144:8090/strela?type=http");
r->add("Radio Studio B|http://radio.studiob.rs:8004/");
r->add("Radio Sunset|http://cmr-hosting.com:8425/stream");
r->add("Radio S|https://53be5ef2d13aa.streamlock.net/asmedia/radios/playlist.m3u8");
r->add("Radio S|https://5bc45691ca49f.streamlock.net/asmedia/radios/playlist.m3u8");
r->add("Radio Užice|http://uzice.yunethosting.net:8000/stream");
r->add("Radio VIP|http://vip128.streaming.rs:8110/listen.pls");
r->add("Radio Zavicaj Plus Godačica|http://s39.myradiostream.com:14870/listen.pls");
r->add("Radio Zelengrad - Milwaukee - USA|http://usa5.fastcast4u.com:16276/;stream.nsv");
r->add("Radio Zlatibor|http://stream11.shoutcastsolutions.com:8002/;stream.nsv");
r->add("Radio Šajkaška|http://91.228.254.72:8000/listen.pls");
r->add("Red radio Beograd|https://stream.redradio.rs/sid=1");
r->add("Resavski Radio Despotovac|http://www.resavski.rs/play/resavski-winamp-128.pls");
r->add("Rock Radio Belgrade (Рок Радио Београд)|https://mastermedia.shoutca.st/proxy/rockradio?mp=/stream");
r->add("Saska radio|http://176.9.59.144:8056/listen.pls");
r->add("Sun Radio Novi Sad|http://stream.radiojar.com/4qawu2xta2zuv.mp3");
r->add("Super FM|http://onair.superfm.rs/superfm.mp3");
r->add("Szabadkai Magyar Rádió|http://breddstream.unrealhosting.hu:4110/;");
r->add("TDI Classics 80' 90'|http://streaming.tdiradio.com:8000/classics.mp3");
r->add("TDI House|http://streaming.tdiradio.com:8000/house.mp3");
r->add("TDI Radio - Bez Reklama|http://streaming.tdiradio.com:8000/tdiradiobezreklama");
r->add("TDI Radio - Chill Out|http://streaming.tdiradio.com:8000/chillout");
r->add("TDI Radio - Classics|http://streaming.tdiradio.com:8000/classics");
r->add("TDI Radio - Domaćica|http://streaming.tdiradio.com:8000/domacica");
r->add("TDI Radio - Love|http://streaming.tdiradio.com:8000/love");
r->add("TDI Radio - Pop RnB Hits|http://streaming.tdiradio.com:8000/poprnbhits");
r->add("TDI Radio - Top 40|http://streaming.tdiradio.com:8000/top40");
r->add("TDI Radio|http://streaming.tdiradio.com:8000/tdiradio");
r->add("Top FM Radio 106.8 Belgrade|http://live64.topfm.rs:8000/");
r->add("UnderGRAND Radio|http://stream.zeno.fm/rp1swb5pgzzuv");
r->add("Usce Shopping Radio|http://naxidigital-usce128.streaming.rs:8000/;stream.nsv");
r->add("VIP Radio|http://vip128.streaming.rs:8110/;stream.nsv");
r->add("Vladix 2 Rock|http://vladix.dukahosting.com:8022/;stream.nsv");
r->add("Vladix 3 Soft|http://79.142.73.156:8676/;stream.nsv");
r->add("Vladix 4 Rok|http://vladix.dukahosting.com:8010/;stream.nsv");
r->add("Vladix Radio|http://vladix.dukahosting.com:8000/;stream.nsv");
r->add("Vudulicious Caffe Radio|http://109.206.96.34:8200/;stream.nsv");
r->add("WTF Radio|http://live.wtfradio.rs/wtfradio.mp3");
r->add("YuEco Radio|https://s1.skeletor.rs/yueco");
r->add("iFM Narodni Radio|http://91.228.254.72:7000/;stream.nsv");
r->add("iFM Radio|http://91.228.254.72:8000/;stream.nsv");
r->add("naxi radio - cafe radio|http://naxidigital-cafe128.streaming.rs:8020/;stream.nsv");
r->add("naxi radio - rock|http://naxidigital-rock128.streaming.rs:8180/;stream.nsv");
r->add("radio gaga|https://onlineradiobox.com/json/rs/gaga/play?platform=web");
r->add("radioaparat|http://ca3.rcast.net:8060/");
r->add("РТС - Радио Београд - 1|https://rtsradio-live.morescreens.com/RTS_2_001/audio/chunklist.m3u8");
r->add("РТС - Радио Београд - 1|https://rtsradio-live.morescreens.com/RTS_2_001/audio/chunklist.m3u8");
r->add("РТС - Радио Београд - 1|https://rtsradio-live.morescreens.com/RTS_2_001/audio/chunklist.m3u8");
r->add("РТС - Радио Београд - 202|https://rtsradio-live.morescreens.com/RTS_2_004/audio/chunklist.m3u8");
r->add("РТС - Радио Београд - 2|https://rtsradio-live.morescreens.com/RTS_2_002/audio/chunklist.m3u8");
r->add("РТС - Радио Београд - 3|https://rtsradio-live.morescreens.com/RTS_2_003/audio/chunklist.m3u8");
r->add("РТС - Радио Београд - Џубокс|https://rtsradio-live.morescreens.com/RTS_2_007/audio/chunklist.m3u8");
r->add("РТС - Радио Београд - Вртешка|https://rtsradio-live.morescreens.com/RTS_2_008/audio/chunklist.m3u8");
r->add("РТС - Радио Београд - Плетеница|https://rtsradio-live.morescreens.com/RTS_2_005/audio/chunklist.m3u8");
r->add("РТС - Радио Београд - Рокенролер|https://rtsradio-live.morescreens.com/RTS_2_006/audio/chunklist.m3u8");
r->add("Радио Београд - 1|https://rtsradio-live.morescreens.com/RTS_2_001/audio/chunklist.m3u8");
}

void Stations::add_bosnia(Fl_Browser *r)
{
r->add("_102.1 TUZLA FM|https://canli.arabeskinmerkezi.com/9180/stream");
r->add("Radio DAŠ|http://158.69.119.6:8095/;&type=mp3");
r->add("Radiopostaja Mir - Međugorje|http://mirm.live/mir.mp3");
r->add("Antena Radio, Jelah Tešanj|https://radio.tnt.ba/radio/8020/live?1616060583");
r->add("BALKAN HiT RADIO - SARAJEVO|https://cast2.asurahosting.com/proxy/balkanhi/stream");
r->add("BH Radio 1|https://webtvstream.bhtelecom.ba/bh_radio1.m3u8");
r->add("BIG 3|http://big3.bigportal.ba:8100/big3?1548653014620");
r->add("Big Radio 1 Banja Luka|http://big1.bigportal.ba:8100/big1");
r->add("Big Radio 4 Domaćica|http://domacica.bigportal.ba:8100/domacica");
r->add("Big2|http://big2.bigportal.ba:8100/big2");
r->add("DUB Radio|http://sc4.streamingpulse.net:8028/");
r->add("HIT Radio Brčko|http://51.254.61.148:8152/;autostart=1");
r->add("Internet Radio GVM|http://178.33.135.246:5726/arabellavie");
r->add("Kakanj, Radio Kakanj|http://cast2.name.ba:8067/");
r->add("Kalman Radio, Sarajevo|http://158.69.119.6:8203/stream");
r->add("Kupreški Radio|http://www.kupreskiradio.com/kupreski.m3u");
r->add("Narodni Radio - Sarajevo|http://server1.tnt.ba:8010/");
r->add("Nes Radio|http://188.40.62.20:8070/;");
r->add("Pakao Radio|https://www.pakaoradio.net/pakaoradio.m3u");
r->add("RADIO MARIA BOSNIA|http://dreamsiteradiocp.com:8034/stream");
r->add("Radio BN|http://stream.rtvbn.com:8522/;.mp3");
r->add("Radio Bir|http://opml.radiotime.com/Tune.ashx?id=s102873");
r->add("Radio Bosanska Krupa|http://195.222.33.217:8091/");
r->add("Radio Brcko District|http://91.191.0.45:8000/listen.pls");
r->add("Radio Busovača|https://ec2s.crolive.com.hr:1510/stream");
r->add("Radio Feral 100.4 Sarajevo|http://185.50.56.3/;stream.nsv");
r->add("Radio Goražde|http://176.9.59.144:8036/stream");
r->add("Radio Ljubić|http://stream.radioljubic.com:8070/;*.mp3");
r->add("Radio MIR Međugorje|https://radio-medjugorje.com/stream");
r->add("Radio Marija|http://cloudrad.io/radiomariabosnia/listen.pls");
r->add("Radio Plus Posušje|http://www.radioplus.ba/wp-content/uploads/2020/10/STREAM-RADIO-PLUS.pls");
r->add("Radio Posavina Zagreb|http://cmr-hosting.com:8500/;stream.mp3");
r->add("Radio Postaja Odzak|https://livessl.rcast.net/stream/66771/");
r->add("Radio Posušje|http://136.243.144.93:9994/");
r->add("Radio Sarajevo|http://malla.softnet.si:8000/");
r->add("Radio Sarajevo|http://malla.softnet.si:8000/;.mp3");
r->add("Radio Sarajevo|http://malla.softnet.si:8000/listen.pls");
r->add("Radio Sarajevo|https://securestreams5.autopo.st:1853/stream");
r->add("Radio Slon|http://31.47.0.130:88/broadwavehigh.mp3");
r->add("Radio Srebrenik|http://live.radiosrebrenik.ba:7600/");
r->add("Radio Studio 99 Sarajevo|https://c2.radioboss.fm:18249/stream");
r->add("Radio USK|https://radiousk.radioca.st/stream");
r->add("Radio Visoko|http://188.40.62.20:8080/");
r->add("Radio Vogošca|http://188.40.62.20:8018/listen.pls");
r->add("Radios 8 Sarajevo|https://radio8-bhcloud.radioca.st/1.mp3");
r->add("Slon Radio Tuzla|http://31.47.0.130:88/broadwavehigh.mp3?src=1;");
r->add("Srce Krajine|https://srv.mediastriming.com/8330/stream");
r->add("Thrash Metal|http://79.120.77.11:8000/thrashmetal");
r->add("Velkaton|http://188.40.62.20:8044/;stream.mp3?_=1");
r->add("novii|http://s37.myradiostream.com:8120/");
r->add("Čaršija|http://carsija.topstream.net:19406/");
}


void Stations::add_croatia(Fl_Browser *r)
{
r->add("..:: CLUB MUSIC RADIO ::....:: 70s 80s 90s ::..|http://cmr-hosting.com:8030/stream?type=http&nocache=773949");
r->add("..:: CLUB MUSIC RADIO ::....:: CRO HITS ::..|http://cmr-hosting.com:8060/stream?type=http&nocache=823456");
r->add("..:: CLUB MUSIC RADIO ::....:: ExYU POP-ROCK ::..|http://cmr-hosting.com:8080/stream?type=http&nocache=13098");
r->add("..:: CLUB MUSIC RADIO ::....:: Folk ::..|http://cmr-hosting.com:8010/stream?type=http&nocache=401572");
r->add("..:: CLUB MUSIC RADIO ::....:: LOVE SONG ::..|http://cmr-hosting.com:8040/stream?type=http&nocache=869535");
r->add("..:: CLUB MUSIC RADIO ::....:: TAMBURA ::..|http://cmr-hosting.com:8070/stream?type=http&nocache=646624");
r->add("..:: RADiO LuDNiCA :: Original Croatian Internet Radio ::..|http://patmos.cdnstream.com:8222/stream?type=http&nocache=120427");
r->add("Antena ZD|http://live.antenazadar.hr:9000/stream/");
r->add("Antena Zagreb - Live|http://live.antenazagreb.hr:8000/;");
r->add("Antena Zagreb - Xmas|http://live.antenazagreb.hr:8015/;");
r->add("Antena Zagreb Dance|http://live.antenazagreb.hr:8015/");
r->add("Antena Zagreb Hit|http://live.antenazagreb.hr:8011/");
r->add("Antena Zagreb Love|http://live.antenazagreb.hr:8007/");
r->add("Antena Zagreb Rock|http://live.antenazagreb.hr:8019/");
r->add("Antena Zagreb Uživo|http://live.antenazagreb.hr:8002/;");
r->add("Bijelo-plavi radio|http://s8.iqstreaming.com:8028/stream");
r->add("CMC Classic|http://radio-stream.cmc.com.hr:8100/autodj");
r->add("CMC Dalmatina|http://radio-stream.cmc.com.hr:8040/autodj");
r->add("CMC Festival|http://radio-stream.cmc.com.hr:8070/autodj");
r->add("CMC Jugoton|http://radio-stream.cmc.com.hr:8020/autodj");
r->add("CMC Kids|http://radio-stream.cmc.com.hr:8090/autodj");
r->add("CMC Lagano|http://radio-stream.cmc.com.hr:8030/autodj");
r->add("CMC Radio|http://radio-stream.cmc.com.hr:8001/autodj");
r->add("CMC Radio|https://radio-stream.cmc.com.hr:9011/autodj");
r->add("CMC Rock|http://radio-stream.cmc.com.hr:8060/autodj");
r->add("CMC Tambure|http://radio-stream.cmc.com.hr:8050/autodj");
r->add("CMC Zabavni|http://radio-stream.cmc.com.hr:8085/autodj");
r->add("CRASH|http://live.radiocrash.net/");
r->add("City-radio 88.6|http://s8.iqstreaming.com:8058/stream;");
r->add("Club Music Radio Tambura|http://cmr-hosting.com:8070/");
r->add("DI Radio Digital Impulse - Oldies but goldies|http://orion.shoutca.st:8248/stream");
r->add("DI Radio Digital Impulse - Rock Hits|http://orion.shoutca.st:8871/");
r->add("DRUGI PROGRAM - HRVATSKI RADIO|http://23543.live.streamtheworld.com/PROGRAM2.mp3");
r->add("Digital Impulse - ATG Trance|http://orion.shoutca.st:8430/stream");
r->add("Digital Impulse - Ambient Nature Sounds|http://orion.shoutca.st:8157/stream");
r->add("Digital Impulse - Blues|http://orion.shoutca.st:8990/stream");
r->add("Digital Impulse - Christmas Channel|http://orion.shoutca.st:8982/stream");
r->add("Digital Impulse - Classical Channel|http://orion.shoutca.st:8978/stream");
r->add("Digital Impulse - DKR Techouse|http://orion.shoutca.st:8243/stream");
r->add("Digital Impulse - Dance 90|http://orion.shoutca.st:8643/");
r->add("Digital Impulse - Electro Swing & Funk|http://orion.shoutca.st:8506/stream");
r->add("Digital Impulse - Heavy Metal|http://orion.shoutca.st:8165/");
r->add("Digital Impulse - Jazz Channel|http://orion.shoutca.st/tunein/asxjyzz.pls");
r->add("Digital Impulse - Movie Themes|http://orion.shoutca.st/tunein/asxmovie.pls");
r->add("Digital Impulse - Techno|https://orion.shoutca.st/tunein/asxrik.pls");
r->add("Digital Impulse - Vocal Trance|http://orion.shoutca.st:8143/stream");
r->add("Digital Impulse Radio - Ektoplazm PsyRadio|http://orion.shoutca.st:8231/stream");
r->add("Digital Impulse Radio - PsychedelicTribe|http://orion.shoutca.st:8049/stream");
r->add("ENTER Zagreb|http://live.enterzagreb.hr:8023/");
r->add("Extra FM|http://streams.extrafm.hr:8110/;");
r->add("GLAS HRVATSKE - HRVATSKI RADIO|http://20723.live.streamtheworld.com/VOICEOFCROATIA.mp3");
r->add("Gold - Velika Gorica|http://live.goldfm.hr:8068/listen.pls");
r->add("Gold FM|http://live.goldfm.hr:8068/");
r->add("Gradski radio Trogir|https://onlineradiobox.com/json/hr/trogir/play?platform=web");
r->add("Gradski radio Virovitica|https://onlineradiobox.com/json/hr/gradskivirovitica/play?platform=web");
r->add("HKR|http://stream.hkr.hr:8000/hkr.mp3");
r->add("HRT Glas Hrvatske|http://playerservices.streamtheworld.com/m3u/VOICEOFCROATIAAAC.m3u");
r->add("HRT HR 1 - Prvi program|http://playerservices.streamtheworld.com/m3u/PROGRAM1AAC.m3u");
r->add("HRT HR 1 - Prvi program|http://provisioning.streamtheworld.com/pls/PROGRAM1.pls");
r->add("HRT HR 2 - Drugi program|http://playerservices.streamtheworld.com/m3u/PROGRAM2AAC.m3u");
r->add("HRT HR 3 - Treći program|http://playerservices.streamtheworld.com/m3u/PROGRAM3AAC.m3u");
r->add("HRT Radio Dubrovnik|http://playerservices.streamtheworld.com/m3u/DUBROVNIKAAC.m3u");
r->add("HRT Radio Knin|http://playerservices.streamtheworld.com/m3u/KNINAAC.m3u");
r->add("HRT Radio Osijek|http://playerservices.streamtheworld.com/m3u/OSIJEKAAC.m3u");
r->add("HRT Radio Pula|http://playerservices.streamtheworld.com/m3u/PULAAAC.m3u");
r->add("HRT Radio Rijeka|http://playerservices.streamtheworld.com/m3u/RIJEKAAAC.m3u");
r->add("HRT Radio Sljeme|http://playerservices.streamtheworld.com/m3u/SLJEMEAAC.m3u");
r->add("HRT Radio Split|http://playerservices.streamtheworld.com/m3u/SPLITAAC.m3u");
r->add("HRT Radio Zadar|http://playerservices.streamtheworld.com/m3u/ZADARAAC.m3u");
r->add("Hit Radio|http://s8.iqstreaming.com:8012/;stream.mp3");
r->add("Hit Rado Sinj|http://s8.iqstreaming.com:8012/listen.pls?sid=1");
r->add("HrCak - Hrvatski radio Cakovec|http://144.76.39.214:7000/");
r->add("Hrvatski Katolički Radio|https://stream.hkr.hr/hkr.mp3");
r->add("Hrvatski Radio - Drugi Program|http://21223.live.streamtheworld.com/PROGRAM2.mp3");
r->add("Hrvatski Radio - Govorni Program|http://20423.live.streamtheworld.com/HR_TALK.mp3");
r->add("Hrvatski Radio - Knin|http://20723.live.streamtheworld.com/KNIN.mp3");
r->add("Hrvatski Radio - Split|http://21223.live.streamtheworld.com/SPLIT.mp3");
r->add("Hrvatski Radio - Treci Program|http://21223.live.streamtheworld.com/PROGRAM3.mp3");
r->add("Hrvatski radio Karlovac|http://s8.iqstreaming.com:8002/");
r->add("Hrvatski radio Vukovar|http://live.hrv.hr:8000/hrv");
r->add("JR Radio|http://stream.zeno.fm/pdkt234k698uv.mp3");
r->add("Jugoton HIT Radio - Wien/Bec - Vas i nas Radio|http://s8.iqstreaming.com:8060/;stream/1");
r->add("KLFM.org|https://klfmorgborg.radioca.st/stream?type=http&nocache=1089");
r->add("Krugoval|http://144.76.172.23:7043/");
r->add("Laganini FM - Rijeka|http://194.145.208.251:8004/stream?type=http&nocache=149");
r->add("Laganini FM Rijeka|http://194.145.208.251:8004/start/lfmri");
r->add("Laganini FM|http://194.145.208.251:8000/start/lfmzg");
r->add("Narodni Radio - AAAAAAAA!|http://live.narodni.hr:8045/");
r->add("Narodni Radio - Ljubav Je U Zraku|http://live.narodni.hr:8181/");
r->add("Narodni Radio - Ne Pitaj, Samo Sviraj|http://live.narodni.hr:8175/");
r->add("Narodni Radio - Opušteno|http://live.narodni.hr:8039/");
r->add("Narodni Radio - Veselo|http://live.narodni.hr:8051/");
r->add("Narodni Radio Goga|https://cmr-hosting.com:7013/;");
r->add("Naxi House|http://naxidigital-house128.streaming.rs:8000/listen.pls");
r->add("Novi Radio Zadar|http://s8.iqstreaming.com:8022/stream");
r->add("Obiteljski Radio Ivanić|http://s8.iqstreaming.com:8080/stream");
r->add("Online Radio Extra Kneginec|http://stream.zeno.fm/c4kvver9bm8uv");
r->add("Online Radio Kneginec|http://stream.zeno.fm/yetzdv442k8uv");
r->add("PRVI PROGRAM - HRVATSKI RADIO|http://21223.live.streamtheworld.com/PROGRAM1.mp3");
r->add("Petrinjski radio|http://s8.iqstreaming.com:8062/");
r->add("Pitomi Radio|http://194.145.208.251:8022/stream?1580651040750.mp3");
r->add("Pomorski Radio Bakar|https://onlineradiobox.com/json/hr/pomorski/play?platform=web");
r->add("Poslovni FM|https://ec2s.crolive.com.hr:2665/stream");
r->add("RADIO DUBROVNIK|http://21223.live.streamtheworld.com/DUBROVNIK.mp3");
r->add("RADIO KNIN|http://23603.live.streamtheworld.com/KNIN.mp3");
r->add("RADIO MARIA CROATIA|http://dreamsiteradiocp4.com:8080/stream");
r->add("RADIO MARIA|http://dreamsiteradiocp.com:8026/stream?type=http&nocache=215");
r->add("RADIO SPLIT - HRVATSKI RADIO|http://23543.live.streamtheworld.com/SPLIT.mp3");
r->add("Radio 057|http://streaming.zadar.net:8000/radio057");
r->add("Radio 101|http://live.radio101.hr:9531/stream.mp3");
r->add("Radio 105 Selnica (HR)|https://azuracast.novi-net.net/radio/8050/radio105.aac");
r->add("Radio 808 Zagreb|https://808proxy.contrib.hr/");
r->add("Radio 808|http://stream.radio808.info:8003/listen.pls");
r->add("Radio 92 FM|https://onlineradiobox.com/json/hr/92fm/play?platform=web");
r->add("Radio Antena|http://live.antenazadar.hr:9000/;?type=http&nocache=10737");
r->add("Radio BINA|http://listen.radioking.com/radio/372715/stream/422872");
r->add("Radio Banovina|http://stream1.radio-banovina.hr:8008/;");
r->add("Radio Biograd na Moru|https://onlineradiobox.com/json/hr/bnm/play?platform=web");
r->add("Radio Blagovesti|http://radio.manastir-lepavina.org:8000/listen.pls");
r->add("Radio Brac|http://s8.iqstreaming.com:8066/listen.pls");
r->add("Radio Centar Studio Poreč|http://radiocentar.hr:8282/mp3");
r->add("Radio DJ Grga|http://cmr-hosting.com:8430/stream?type=http&nocache=343");
r->add("Radio Dalmacija - Fjaka|http://c5.hostingcentar.com:8203/stream");
r->add("Radio Dalmacija - Furešta|http://c5.hostingcentar.com:8215/stream");
r->add("Radio Dalmacija - Hajdučke|http://c5.hostingcentar.com:8221/stream");
r->add("Radio Dalmacija - Mix (PartyMix)|http://c5.hostingcentar.com:8281/stream");
r->add("Radio Dalmacija - Oliver|http://c5.hostingcentar.com:8275/stream");
r->add("Radio Dalmacija - Oliver|http://c5.hostingcentar.com:8275/stream");
r->add("Radio Dalmacija - Rokija|http://c5.hostingcentar.com:8209/stream");
r->add("Radio Dalmacija|http://shoutcast.pondi.hr:8000/listen.pls");
r->add("Radio Daruvar|http://85.17.172.242:8070/");
r->add("Radio Deejay HR|http://live.deejay.hr:7002/;");
r->add("Radio Delta 97,0 MHz|http://185.62.75.24:8010/stream?type=http&nocache=3910");
r->add("Radio Delta Metković|http://185.62.75.24:8010/");
r->add("Radio Dunav 101,5 FM Vukovar|http://cp4.shoutcheap.com:8111/listen.pls");
r->add("Radio Eurostar Umag|http://mcp1.mydataknox.com:8012/stream");
r->add("Radio Gorski kotar|http://144.76.39.214:9500/stream.mp3");
r->add("Radio Grubišno Polje|https://ec2s.crolive.com.hr:8215/stream");
r->add("Radio Hrvat|http://213.239.215.181:9036/stream");
r->add("Radio Ilok|http://178.32.146.187:5172/stream");
r->add("Radio Imotski 107.4 FM|http://radioimotski.radioca.st/stream");
r->add("Radio Jaska|https://uk1.streamingpulse.com/ssl/RadioJaska");
r->add("Radio Kaj|https://s8.iqstreaming.com:2020/stream/radio-kaj2/stream");
r->add("Radio Koprivnica|http://194.152.206.205:8000/");
r->add("Radio Korzo|http://www.radiokorzo.hr/stream/premium.pls");
r->add("Radio Križevci|https://s8.iqstreaming.com:8048/stream");
r->add("Radio Lošinj / Radio Jadranka|https://n01.radiojar.com/ppdr62bnmrhvv?rj-ttl=5&rj-tok=AAABgT0eDuMA6RAqze3AMbsluQ");
r->add("Radio Ludbreg|http://85.25.135.86:23573/");
r->add("Radio Ludnica|http://192.111.140.6:8222/");
r->add("Radio M 90,1 MHz|http://radiomvelaluka.ddns.net:8000/stream");
r->add("Radio Makarska Riviera|http://85.25.135.86:8018/stream?type=http&nocache=21309");
r->add("Radio Makarska Rivijera|http://85.25.135.86:8018/");
r->add("Radio Marija Bistrica|http://178.218.163.171:8024/stream");
r->add("Radio Marija Hrvatska|https://dreamsiteradiocp2.com/proxy/rmcroatia?mp=/stream");
r->add("Radio Marija|http://dreamsiteradiocp4.com:8080/");
r->add("Radio Martin|http://genf196.server4you.de:8585/");
r->add("Radio Media Servis|http://live.mediaservis.hr:8084/stream?type=http&nocache=557757");
r->add("Radio Moslavina|http://144.76.172.23:7049/");
r->add("Radio NACIONAL|https://nnc1-bpmmc501.radioca.st/stream");
r->add("Radio Nacional |https://nnc1-bpmmc501.radioca.st/stream");
r->add("Radio Nova Gradiška|http://comet.shoutca.st:8050/");
r->add("Radio Novska|http://genf196.server4you.de:8686/");
r->add("Radio Orahovica|https://ec2s.crolive.com.hr:2595/stream");
r->add("Radio Otocac|http://s8.iqstreaming.com:8024/stream");
r->add("Radio Ploce 64,5 MHz|http://178.218.163.171:8010/ploce");
r->add("Radio Pravi Zivot u Bogu|http://46.28.49.164:7804/;stream/1");
r->add("Radio Prkos|http://eu7.fastcast4u.com:6124/stream");
r->add("Radio Quirinus 91.7|http://s8.iqstreaming.com:8064/stream");
r->add("Radio Ritam Šibenik|https://ec2s.crolive.com.hr:8455/stream");
r->add("Radio Rojc, Pula|http://radiorojc.streamradio.com.hr:8972/;");
r->add("Radio Roza|http://stream.radio-roza.org/live.mp3");
r->add("Radio Samobor|http://185.150.235.162/");
r->add("Radio Slatina|http://85.17.172.242:8020/live2.mp3");
r->add("Radio Slavonija|http://s8.iqstreaming.com:8026/listen.pls");
r->add("Radio Slunj  95.2|http://s3.iqstreaming.com/tunein.php/slunj/playlist.pls");
r->add("Radio Student Zagreb|http://161.53.122.184:8000/AAC128.aac");
r->add("Radio Student|http://www.radiostudent.hr/AAC128.pls");
r->add("Radio Sunce|http://shoutcast.pondi.hr:8002/;*.mp3");
r->add("Radio Techno Dance Kneginec|http://stream.zeno.fm/8d2pyzm5wp8uv");
r->add("Radio Vinkovci|https://onlineradiobox.com/json/hr/vinkovci/play?platform=web");
r->add("Radio Vrbovec 94.5|http://c2.hostingcentar.com:9452/;");
r->add("Radio Zlatar|http://144.76.172.23:7059/");
r->add("Radio stubica|http://radiostubica.hc.hr:7006/stream");
r->add("Radio Šibenik|http://144.76.219.22:8215/stream.mp3?ver=421911");
r->add("Radio100.5 Student Zagreb|http://www.radiostudent.hr/aacPlus48.pls");
r->add("Radio101 rock|http://live.radio101.hr:9578/");
r->add("Radio101|http://live.radio101.hr:9531/");
r->add("Rovinj FM|http://rovinj.fm:8000/");
r->add("Slavonski Radio|https://ec2s.crolive.com.hr:8035/stream");
r->add("Soundset Ragusa|http://178.218.163.171:8012/stream");
r->add("Studentski radio UNIOS|http://radio.unios.hr:8000/stream.mp3");
r->add("Super Radio|https://mcp1.mydataknox.com:2000/tunein/stream_4/stream/pls");
r->add("TLIG Radio Croatian|http://46.28.49.164:7804/stream");
r->add("Top Radio|http://c5.hostingcentar.com:8000/streams/topradio/");
r->add("Top Radio|https://c5.hostingcentar.com/streams/topradio/");
r->add("Trend Radio Karlovac|https://trend.com.hr/stream/playlist.php?name=listen.asx");
r->add("ULTRA Split|http://c5.hostingcentar.com:8061/listen.pls?sid=1");
r->add("Ultra Split|http://c5.hostingcentar.com:8061/;stream/1");
r->add("Unidu radio|http://true.etfos.hr:8000/unidu");
r->add("Yammat FM|https://stream.yammat.fm/radio/8000/yammat.mp3");
r->add("ZFM|https://ec2s.crolive.com.hr:7015/stream");
r->add("Zabavni radio|https://genf196.server4you.de:8585/");
r->add("Zagorski radio|https://s8.iqstreaming.com:2020/stream/zagorski/stream");
r->add("https://clubmusic-1.com/|http://cmr-hosting.com:8050/stream?type=http&nocache=5796");
r->add("Županijski Radio Virovitica|https://radio.icv.hr/9300/stream");
}



void Stations::add_switzerland(Fl_Browser *r)
{
r->add("1.FM - A List 80s|http://strm112.1.fm/back280s_mobile_mp3");
r->add("1.FM - Absolute 70's Pop Radio|http://sc-70s.1.fm:8658/");
r->add("1.FM - Absolute 70's Pop Radio|http://strm112.1.fm/70s_mobile_mp3");
r->add("1.FM - Absolute 90s Party Zone Radio|http://strm112.1.fm/partyzone90s_mobile_mp3");
r->add("1.FM - Absolute Country Hits Radio|http://strm112.1.fm/acountry_mobile_mp3");
r->add("1.FM - Absolute Pop Latino Radio|http://strm112.1.fm/latino_mobile_mp3");
r->add("1.FM - Absolute TOP 40 Radio|http://sc-t40.1.fm:7016/");
r->add("1.FM - Absolute TOP 40 Radio|http://strm112.1.fm/top40_mobile_mp3");
r->add("1.FM - Absolute Trance (Euro) Radio|http://strm112.1.fm/trance_mobile_mp3");
r->add("1.FM - Acappella Radio|http://strm112.1.fm/acpl_mobile_mp3");
r->add("1.FM - Adore Jazz Radio|http://strm112.1.fm/ajazz_mobile_mp3");
r->add("1.FM - Adore Jazz Radio|http://strm112.1.fm/ajazz_mobile_mp3");
r->add("1.FM - Adult Urban Hits Choice Radio|http://strm112.1.fm/oldschool_mobile_mp3");
r->add("1.FM - Afterbeat Electronica Radio|http://strm112.1.fm/electronica_mobile_mp3");
r->add("1.FM - All Euro 80's Radio|http://strm112.1.fm/80s_90s_mobile_mp3");
r->add("1.FM - All Times & Urban Gospel Radio|http://strm112.1.fm/gospel_mobile_mp3");
r->add("1.FM - All Times Hits|http://185.33.21.111/allmixedup_mobile_mp3");
r->add("1.FM - Alternative Rock X Hits Radio|http://strm112.1.fm/x_mobile_mp3");
r->add("1.FM - Always-Christmas Radio|http://strm112.1.fm/christmas_mobile_mp3");
r->add("1.FM - Ambient Psychill|http://strm112.1.fm/ambientpsy_mobile_mp3");
r->add("1.FM - America's Best Ballads Radio|http://strm112.1.fm/onelive_mobile_mp3");
r->add("1.FM - Amsterdam Trance Radio|http://strm112.1.fm/atr_mobile_mp3");
r->add("1.FM - BOM Psytrance Radio|http://strm112.1.fm/psytrance_mobile_mp3");
r->add("1.FM - Back To The 50's & 60's Radio|http://strm112.1.fm/60s_70s_mobile_mp3");
r->add("1.FM - Bay Smooth Jazz Radio|http://strm112.1.fm/smoothjazz_mobile_mp3");
r->add("1.FM - Blues Radio|http://strm112.1.fm/blues_mobile_mp3");
r->add("1.FM - Bombay Beats India Radio|http://strm112.1.fm/bombaybeats_mobile_mp3");
r->add("1.FM - Bossa Nova Hits|http://strm112.1.fm/bossanova_mobile_mp3");
r->add("1.FM - Cafe Radio|http://strm112.1.fm/caferadio_mobile_mp3");
r->add("1.FM - Chillout Lounge Radio|http://strm112.1.fm/chilloutlounge_mobile_mp3");
r->add("1.FM - Circuit Pride Radio|http://strm112.1.fm/circuitpride_mobile_mp3");
r->add("1.FM - Classic Country Radio|http://strm112.1.fm/ccountry_mobile_mp3");
r->add("1.FM - Classic Rock Replay Radio|http://strm112.1.fm/crock_mobile_mp3");
r->add("1.FM - Club 1 Radio|http://strm112.1.fm/club_mobile_mp3");
r->add("1.FM - Costa Del Mar|http://strm112.1.fm/costadelmarchillout_mobile_mp3");
r->add("1.FM - Country One Radio|http://strm112.1.fm/country_mobile_mp3");
r->add("1.FM - Dance One Radio|http://strm112.1.fm/dance_mobile_mp3");
r->add("1.FM - Deep House Radio|http://strm112.1.fm/deephouse_mobile_mp3");
r->add("1.FM - Deep Techno & Deep House|http://strm112.1.fm/deeptech_mobile_mp3");
r->add("1.FM - Destination: SPA Radio|http://strm112.1.fm/spa_mobile_mp3");
r->add("1.FM - Disco Ball 70's-80's Radio|http://strm112.1.fm/disco_mobile_mp3");
r->add("1.FM - Dubstep Forward Radio|http://strm112.1.fm/dubstep_mobile_mp3");
r->add("1.FM - Eternal Praise & Worship Radio|http://strm112.1.fm/praise_mobile_mp3");
r->add("1.FM - Exitos del Ayer Radio|http://strm112.1.fm/spanisholdies_mobile_mp3");
r->add("1.FM - Funky Express Radio|http://185.33.22.15:11121/");
r->add("1.FM - Gorilla FM Radio|http://strm112.1.fm/gorillafm_mobile_mp3");
r->add("1.FM - High Voltage Radio|http://strm112.1.fm/highvoltage_mobile_mp3");
r->add("1.FM - Ibiza Chill Tropical|http://strm112.1.fm/ibizachill_mobile_mp3?aw_0_req.gdpr=true");
r->add("1.FM - Italia On Air Radio|http://strm112.1.fm/italiaonair_mobile_mp3");
r->add("1.FM - Jamz Radio|http://strm112.1.fm/jamz_mobile_mp3");
r->add("1.FM - Kids FM Radio|http://strm112.1.fm/kidsfm_mobile_mp3");
r->add("1.FM - Love Classics Radio|http://strm112.1.fm/loveclassics_mobile_mp3");
r->add("1.FM - MPB Hits Radio|http://strm112.1.fm/mpb_mobile_mp3");
r->add("1.FM - Magic 80 Radio|http://strm112.1.fm/magic80_mobile_mp3");
r->add("1.FM - Movie Soundtrack|http://strm112.1.fm/moviesoundtracks_mobile_mp3");
r->add("1.FM - Otto's Baroque Music Radio|http://strm112.1.fm/baroque_mobile_mp3");
r->add("1.FM - Otto's Opera House Music Radio|http://strm112.1.fm/opera_mobile_mp3");
r->add("1.FM - Radio Gaia|http://strm112.1.fm/radiogaia_mobile_mp3");
r->add("1.FM - ReggaeTrade Radio|http://strm112.1.fm/reggae_mobile_mp3");
r->add("1.FM - Rock Classics Radio|http://strm112.1.fm/rockclassics_mobile_mp3");
r->add("1.FM - Samba Hits Brazil Radio|http://strm112.1.fm/samba_mobile_mp3");
r->add("1.FM - Samba Rock Radio|http://strm112.1.fm/sambarock_mobile_mp3");
r->add("1.FM - Sax4Love|http://strm112.1.fm/sax4ever_mobile_mp3");
r->add("1.FM - Sertaneja Hits Radio|http://strm112.1.fm/sertanejo_mobile_mp3");
r->add("1.FM - Slow Jamz Radio|http://strm112.1.fm/slowjamz_mobile_mp3");
r->add("1.FM - Sunshine|https://strm112.1.fm/allmixedup_mobile_mp3?");
r->add("1.FM - Top Fiesta Radio|http://strm112.1.fm/spanishparty_mobile_mp3");
r->add("1.FM - Total Hits En Español Radio|http://strm112.1.fm/spanishtophits_mobile_mp3");
r->add("1.FM Beloved Ballads|https://strm112.1.fm/onelive_mobile_mp3?");
r->add("1.FM Essential Classical|http://strm112.1.fm/polskafm_mobile_mp3");
r->add("1.fm Back To The 50's |https://strm112.1.fm/60s_70s_mobile_mp3?");
r->add("1.fm Movie Soundtrack Hits|https://strm112.1.fm/moviesoundtracks_mobile_mp3?");
r->add("1.fm Otto's Baroque music|http://strm112.1.fm/baroque_mobile_aac");
r->add("1.fm Otto's Classical music|https://strm112.1.fm/classical_mobile_aac");
r->add("1.fm top rap|https://strm112.1.fm/jamz_mobile_mp3?aw_0_req.gdpr=true&listenerid=bc625eb7aaf609dd3942dc610e46ed40&awparams=companionAds%3Atrue");
r->add("80s Forever - We Keep The 80s Alive|http://azuracast.ssl-stream.com/radio/8050/256.mp3");
r->add("80s Forever - We Keep The 80s Alive|https://premium.shoutcastsolutions.com/radio/8050/256.mp3");
r->add("A Fine Jazz Gumbo Radio|http://streaming.smartradio.ch:9002/stream");
r->add("A Fine Jazz Gumbo Radio|https://streaming.smartradio.ch:9502/stream");
r->add("Ahuga laut.fm|http://stream.laut.fm/ahuga");
r->add("Ambi Nature Radio|https://nature-rex.radioca.st/stream");
r->add("Arc Musique|https://arcmusique.ice.infomaniak.ch/arcmusique-128.mp3");
r->add("Audioasyl|http://stream.audioasyl.net:8000/audioasyl");
r->add("Bibelradio NT Psalmen|http://rs1.stream24.org:9160/stream");
r->add("Bibelradio|http://rs1.stream24.org:8690/stream");
r->add("Bless Radio|https://streaming12.elitecomunicacion.es:8106/stream");
r->add("Break Radio|https://breakradio.ice.infomaniak.ch/breakradio-192.mp3");
r->add("BurningStation.com|https://server1.streamserver-unlimited.de:2199/tunein/iu245.pls");
r->add("Christmas Radio|http://xmasfm1.dmd2streaming.com/christmasradiofm-128.mp3");
r->add("Couleur3|http://stream.srg-ssr.ch/m/couleur3/aacp_96");
r->add("Electro Radio|https://www.electroradio.fm/stream.m3u");
r->add("Energy Basel (NRJ)|https://energybasel.ice.infomaniak.ch/energybasel-high.mp3");
r->add("Energy Bern (NRJ)|http://broadcast.infomaniak.ch/energybern-high.mp3");
r->add("Energy Blick Trendz|http://energyzuerich.ice.infomaniak.ch/energyzuerich-high.mp3");
r->add("Energy St. Gallen (NRJ)|https://energystgallen.ice.infomaniak.ch/energystgallen-high.mp3");
r->add("Energy Zürich (NRJ)|http://broadcast.infomaniak.ch/energyzuerich-high.mp3");
r->add("FLASHBACK FM|https://flashback.streambase.ch/001");
r->add("FLASHBACK FM|https://flashback.streambase.ch/001");
r->add("FM1 Nord|http://radiofm1.ice.infomaniak.ch/radiofm1-128.mp3");
r->add("Framboase|http://framboase.ice.infomaniak.ch/framboase-128.mp3");
r->add("GDS.FM|http://gdsfm.out.airtime.pro:8000/gdsfm_a");
r->add("Galaxy Radio|https://radio.torrentgalaxy.su:25374/stream.m3u");
r->add("Glaubenskampf Bibel Radio|https://streams.radio.co/s06c02a443/listen");
r->add("Global FM|http://globalfm.ice.infomaniak.ch/globalfm-high.mp3");
r->add("Gnu Radio - Metal FM|https://fluxfm.streamabc.net/flx-metalfm-mp3-320-9154971?sABC=61s83r32%230%2389nqs1p1q8rrq2q126260sp7877or6oo%23fgernzf.syhksz.qr&amsparams=playerid:streams.fluxfm.de;skey:1643658802");
r->add("Gorilla.fm|https://str1.pcradio.ru/one_gorilla-med");
r->add("Gorilla.fm|https://strm112.1.fm/gorillafm_mobile_mp3");
r->add("Gottes Radio|http://stream.laut.fm/gottesradio.m3u");
r->add("Grrif|https://grrif.ice.infomaniak.ch/grrif-high.mp3");
r->add("IP music slow (128 kbps AAC)|http://live7.avf.ch:8000/ipmusicslowaacp128");
r->add("IP music slow (96 kbps AAC)|http://live7.avf.ch:8000/ipmusicslowaacp96");
r->add("IP music|http://live9.avf.ch:8000/ipmusicaacplus96");
r->add("JAMES FM|https://jamesfm.ice.infomaniak.ch/jamesfm.mp3");
r->add("Jazzology Radio|https://c2.radioboss.fm:18094/stream");
r->add("Jukebox - Kreuzberg Swiss|https://simba.streampanel.cloud:11050/stream");
r->add("KTFM / Global Sport|http://live9.avf.ch:8000/globalfmdabge");
r->add("Kanal Bethesda|http://162.13.25.174/a2dd2q0kb");
r->add("Kanal K|https://streamer1.kanalk.ch/kanalk.mp3");
r->add("Kontrafunk|https://s5.radio.co/sca4082ebb/listen");
r->add("Kontrafunk|https://s5.radio.co/sca4082ebb/listen");
r->add("LFM|http://lausannefm.ice.infomaniak.ch/lausannefm-high.mp3");
r->add("Loose Antenna|https://stream.looseantenna.fm/radio/8000/default.mp3");
r->add("Lounge Radio|http://de1.streamhosting.ch/");
r->add("Melody Vintage forever|https://str0.creacast.com/melody2");
r->add("NRJ Léman 103,6 FM|http://cdn.nrjaudio.fm/audio1/ch/50001/mp3_128.mp3");
r->add("New Clear Radio|http://live.ncradio.fm/128");
r->add("New Clear Radio|http://live.ncradio.fm/320");
r->add("One Dance Ticino|https://ice15.fluidstream.net/onedancech.aac");
r->add("One FM New-Hits|https://webradio0001.ice.infomaniak.ch/webradio0001-128.mp3");
r->add("One FM|http://onefm.ice.infomaniak.ch/onefm-high.mp3");
r->add("Open Broadcast|http://stream.openbroadcast.org/openbroadcast.flac");
r->add("Open Broadcast|https://www.openbroadcast.org/stream/openbroadcast");
r->add("Pineapple Juice|http://stream.laut.fm/pineapplejuice");
r->add("Pineapplejuice|http://stream.laut.fm/pineapplejuice");
r->add("Pirates Radio|http://pirates.mine.nu:8080/pirates.mp3");
r->add("Planet Ambi HD|http://www.planetambi.com/tunein/planetambi.pls");
r->add("Powerup Radio|http://stream.powerup.ch/powerupradio-192.mp3");
r->add("Public Domain Classical Radio|http://relay.publicdomainradio.org/classical.mp3");
r->add("Public Domain Classical Radio|http://relay.publicdomainradio.org/classical.mp3");
r->add("Public Domain Classical|http://relay.publicdomainproject.org/classical.mp3.m3u");
r->add("Public Domain Jazz Radio|http://relay.publicdomainradio.org/jazz_swing.mp3");
r->add("Public Domain Jazz|http://relay.publicdomainproject.org/jazz_swing.mp3.m3u");
r->add("Public Domain Jazz|http://relay.publicdomainradio.org/jazz_swing.aac.m3u");
r->add("R102|http://94.23.66.155:9334/listen.pls");
r->add("RADIO MARIA SWITZERLAND|http://dreamsiteradiocp2.com:8106/stream");
r->add("RADIO ROTATION|http://stream.laut.fm/radio-rotation");
r->add("RADIO SWISS CLASSICA ITALIA|https://stream.srg-ssr.ch/m/rsc_it/mp3_128");
r->add("RADIO SWISS CLASSICA ITALIA|https://stream.srg-ssr.ch/rsc_it/aacp_96.m3u");
r->add("RADIO SWISS CLASSICA ITALIA|https://stream.srg-ssr.ch/rsc_it/mp3_128.m3u");
r->add("RFJ|https://rfj.ice.infomaniak.ch/rfj-high.mp3");
r->add("RJB|https://rjb.ice.infomaniak.ch/rjb-high.mp3");
r->add("ROCKSTATION's Broadcast|http://radio2.stream24.net:8130/live.mp3");
r->add("RSI Rete Due|http://stream.srg-ssr.ch/m/retedue/mp3_128");
r->add("RSI Rete Due|http://stream.srg-ssr.ch/retedue/aacp_32.m3u");
r->add("RSI Rete Tre|http://stream.srg-ssr.ch/m/retetre/mp3_128");
r->add("RSI Rete Tre|http://stream.srg-ssr.ch/retetre/aacp_32.m3u");
r->add("RSI Rete Uno|http://stream.srg-ssr.ch/m/reteuno/mp3_128");
r->add("RSI Rete Uno|http://stream.srg-ssr.ch/reteuno/aacp_32.m3u");
r->add("RSR Couleur 3|http://stream.srg-ssr.ch/couleur3/aacp_32.m3u");
r->add("RSR Espace 2|http://stream.srg-ssr.ch/espace-2/aacp_32.m3u");
r->add("RSR La Premiere|http://stream.srg-ssr.ch/la-1ere/aacp_32.m3u");
r->add("RSR Option Musique|http://stream.srg-ssr.ch/option-musique/aacp_32.m3u");
r->add("RTN|https://rtn.ice.infomaniak.ch/rtn-high.mp3");
r->add("RTS Couleur 3|http://stream.srg-ssr.ch/m/couleur3/mp3_128");
r->add("RTS Espace 2|http://stream.srg-ssr.ch/espace-2/mp3_128.m3u");
r->add("RTS Espace 2|http://stream.srg-ssr.ch/m/espace-2/aacp_96");
r->add("RTS La Première|http://stream.srg-ssr.ch/m/la-1ere/mp3_128");
r->add("RTS Option Musique|http://stream.srg-ssr.ch/option-musique/mp3_128.m3u");
r->add("RTS Option Musique|http://stream.srg-ssr.ch/option-musique/mp3_128.m3u");
r->add("RaBe Radio Bern Switzerland|http://stream.rabe.ch/livestream/rabe-mid.mp3");
r->add("RaBe Radio Bern Switzerland|http://stream.rabe.ch:8000/livestream/rabe-mid.mp3");
r->add("Radio 1|http://stream.radio1.ch/128k.m3u");
r->add("Radio 1|https://radio.netstream.ch/128k");
r->add("Radio 24|http://icecast.radio24.ch/radio24");
r->add("Radio 32|http://stream.radio32.ch/radio32");
r->add("Radio 3FACH|http://stream01.3fach.ch:8001/live");
r->add("Radio Argovia|http://icecastgreen.argovia.ch/argovia-rc-96-aac");
r->add("Radio Barix AAC|http://barix.streamguys.net/barix_aacp");
r->add("Radio Basilisk|http://radiobasilisk-64.ice.infomaniak.ch/radiobasilisk-64-128-2.mp3");
r->add("Radio BeO|http://stream11.radiobeo.ch:8000/radiobeo.mp3");
r->add("Radio Beo|https://radiobeo2.mp3.green.ch/beo.mp3");
r->add("Radio Bern1 - main [mp3 128kbps]|http://mp3.radiobern1.ch/radiobern1128k");
r->add("Radio Blitz|http://server9932.streamplus.de:27100/;listen.pls?sid=1");
r->add("Radio Bollwerk|https://radiobollwerk.out.airtime.pro/radiobollwerk_a");
r->add("Radio Central|http://radiocentral.ice.infomaniak.ch/radiocentral-128.mp3");
r->add("Radio Chablais - 100% Français|http://stream.radiochablais.ch/chablais-100francais.mp3");
r->add("Radio Chablais|http://radiochablais.ice.infomaniak.ch/radiochablais-high.mp3");
r->add("Radio Cité Genève|http://statslive.infomaniak.ch/playlist/radiocite/radiocite128.mp3/playlist.m3u");
r->add("Radio Eviva|http://radioeviva.ice.infomaniak.ch/radioeviva-128.mp3");
r->add("Radio Freundesdienst Deutsch|http://radiofd.ice.infomaniak.ch/radiofd.mp3");
r->add("Radio Freundesdienst Schweiz|http://radiofdch.ice.infomaniak.ch/radiofdch.mp3");
r->add("Radio Gloria|https://ch-be06-ice.dmd2streaming.com/radiogloria_lo");
r->add("Radio Gugelhopf|http://uk3.internet-radio.com:8113/stream");
r->add("Radio Gwendalyn|http://stream.radiogwen.ch:8000/radiogwen.m3u");
r->add("Radio Henri Dès|https://17563.live.streamtheworld.com/SP_R2329710.mp3?tdsdk=js-2.9&pname=TDSdk&pversion=2.9&banners=none&burst-time=15&sbmid=5747c33e-8dc4-4308-f95e-816736f4507f");
r->add("Radio Henri Gès|https://17563.live.streamtheworld.com/SP_R2329710.mp3?tdsdk=js-2.9&pname=TDSdk&pversion=2.9&banners=none&burst-time=15&sbmid=5747c33e-8dc4-4308-f95e-816736f4507f");
r->add("Radio Kaiseregg|http://kaiseregg.ice.infomaniak.ch/stream128k.mp3");
r->add("Radio Kaos Caribou|https://rkc.ice.infomaniak.ch/stream");
r->add("Radio Lac|https://radiolac.ice.infomaniak.ch/radiolac-high.mp3");
r->add("Radio LoRa|http://lora.ice.infomaniak.ch/lora.mp3");
r->add("Radio Maria Switzerland|http://dreamsiteradiocp.com:8020/stream");
r->add("Radio Maxxima|https://maxxima.mine.nu/maxxima.mp3");
r->add("Radio Melody|https://fm1melody.ice.infomaniak.ch/fm1melody-128.mp3");
r->add("Radio Morcote International|http://streaming.radiomorcoteinternational.com:8000/;");
r->add("Radio Munot|http://streaming.swisstxt.ch/m/radiomunot/mp3_128");
r->add("Radio Neue Hoffnung|https://stream.mnr.ch/rnh-mp3");
r->add("Radio Number One Dance Ticino|http://ice15.fluidstream.net/onedancech.aac");
r->add("Radio Onyx|http://nr4.newradio.it:9432/listen.pls");
r->add("Radio Ouistiti|http://ouistiti-aac.stream2net.eu:8100/;");
r->add("Radio Ouistiti|http://radioouistiti2.ice.infomaniak.ch/radioouistiti-high.mp3");
r->add("Radio Pilatus|http://radiopilatus.bcast.infomaniak.ch/pilatus128.mp3");
r->add("Radio Qfm|https://stream.qfm.network:8443/stream");
r->add("Radio Radius (AAC)|http://relay.radio.ethz.ch/sender.aac.m3u");
r->add("Radio Radius (mp3)|http://relay.radio.ethz.ch/sender.mp3.m3u");
r->add("Radio Radius (ogg)|http://relay.radio.ethz.ch/sender.ogg.m3u");
r->add("Radio Rocket|https://i9.streams.ovh/sc/radioroc/stream");
r->add("Radio Rottu Oberwallis|http://streams.rro.ch/rro.mp3");
r->add("Radio Rumantsch|http://stream.srg-ssr.ch/m/rr/mp3_128");
r->add("Radio R|http://radior.ice.infomaniak.ch/radior-128.mp3");
r->add("Radio S KSF|https://bienemobil.feste-ip.net/;stream.mp3");
r->add("Radio SRF 1 Aargau Solothurn|http://stream.srg-ssr.ch/regi_ag_so/aacp_32.m3u");
r->add("Radio SRF 1 Basel Baselland|http://stream.srg-ssr.ch/m/regi_bs_bl/aacp_96");
r->add("Radio SRF 1 Basel Baselland|http://stream.srg-ssr.ch/regi_bs_bl/aacp_32.m3u");
r->add("Radio SRF 1 Bern Freibourg Wallis|http://stream.srg-ssr.ch/regi_be_fr_vs/aacp_32.m3u");
r->add("Radio SRF 1 Ostschweiz|http://stream.srg-ssr.ch/regi_ost/aacp_32.m3u");
r->add("Radio SRF 1 Regionaljournal Aargau, Solothurn|http://stream.srg-ssr.ch/m/regi_ag_so/mp3_128");
r->add("Radio SRF 1 Regionaljournal Basel, Baselland|http://stream.srg-ssr.ch/m/regi_bs_bl/mp3_128");
r->add("Radio SRF 1 Regionaljournal Bern, Freiburg, Wallis|http://stream.srg-ssr.ch/m/regi_be_fr_vs/mp3_128");
r->add("Radio SRF 1 Regionaljournal Graubünden|http://stream.srg-ssr.ch/m/regi_gr/mp3_128");
r->add("Radio SRF 1 Regionaljournal Ostschweiz|http://stream.srg-ssr.ch/m/regi_ost/mp3_128");
r->add("Radio SRF 1 Regionaljournal Zürich, Schaffhausen|http://stream.srg-ssr.ch/m/regi_zh_sh/mp3_128");
r->add("Radio SRF 1 Zentralschweiz|http://stream.srg-ssr.ch/m/regi_zentr/mp3_128");
r->add("Radio SRF 1 Zentralschweiz|http://stream.srg-ssr.ch/regi_zentr/aacp_32.m3u");
r->add("Radio SRF 1 Zürich Schaffhausen|http://stream.srg-ssr.ch/regi_zh_sh/aacp_32.m3u");
r->add("Radio SRF 1|http://stream.srg-ssr.ch/drs1/aacp_32.m3u");
r->add("Radio SRF 2 Kultur|http://stream.srg-ssr.ch/drs2/aacp_32.m3u");
r->add("Radio SRF 2 Kultur|http://stream.srg-ssr.ch/drs2/mp3_128.m3u");
r->add("Radio SRF 2 Kultur|http://stream.srg-ssr.ch/m/drs2/mp3_128");
r->add("Radio SRF 2 Kultur|https://stream.srg-ssr.ch/m/drs2/aacp_32");
r->add("Radio SRF 2 Kultur|https://stream.srg-ssr.ch/m/drs2/aacp_96");
r->add("Radio SRF 3|http://stream.srg-ssr.ch/drs3/aacp_32.m3u");
r->add("Radio SRF 3|https://stream.srg-ssr.ch/m/drs3/aacp_32");
r->add("Radio SRF 3|https://stream.srg-ssr.ch/m/drs3/aacp_96");
r->add("Radio SRF 4 News|http://stream.srg-ssr.ch/drs3/aacp_96.ram");
r->add("Radio SRF 4 News|http://stream.srg-ssr.ch/drs4news/aacp_32.m3u");
r->add("Radio SRF 4 News|https://stream.srg-ssr.ch/m/drs4news/aacp_32");
r->add("Radio SRF 4 News|https://stream.srg-ssr.ch/m/drs4news/aacp_96");
r->add("Radio SRF Musikwelle|http://stream.srg-ssr.ch/drsmw/aacp_32.m3u");
r->add("Radio SRF Virus - Indie Rock|http://streaming.swisstxt.ch/m/drsvirus/mp3_128");
r->add("Radio SRF Virus|http://stream.srg-ssr.ch/drsvirus/aacp_32.m3u");
r->add("Radio SRF Virus|http://stream.srg-ssr.ch/drsvirus/aacp_96.ram");
r->add("Radio Sans Chaine|http://radio-sans-chaine.ice.infomaniak.ch/radiosanschaine.aac");
r->add("Radio Stadtfilter Winterthur|http://stream.stadtfilter.net:8406/stadtfilter.mp3");
r->add("Radio Suisse Classique|http://stream.srg-ssr.ch/m/rsc_fr/mp3_128");
r->add("Radio Suisse Classique|http://www.surfmusik.de/m3u/station/radio-suisse-classique,16403.m3u");
r->add("Radio Summernight|https://stream.laut.fm/radiosummernight");
r->add("Radio Sunshine|http://sunshineradio.ice.infomaniak.ch/sunshineradio-128.mp3");
r->add("Radio Svizzera Classica|http://stream.srg-ssr.ch/m/rsc_it/mp3_128");
r->add("Radio Svizzera Classica|https://stream.srg-ssr.ch/rsc_it/aacp_96.m3u");
r->add("Radio Swiss Classic French|http://www.radioswissclassic.ch/fr/live/aacp.m3u");
r->add("Radio Swiss Classic French|http://www.radioswissclassic.ch/fr/live/aacp32.m3u");
r->add("Radio Swiss Classic German|http://stream.srg-ssr.ch/m/rsc_de/mp3_128");
r->add("Radio Swiss Classic German|http://www.radioswissclassic.ch/de/live/aacp32.m3u");
r->add("Radio Swiss Classic Italian|http://www.radioswissclassic.ch/it/live/aacp.m3u");
r->add("Radio Swiss Classic Italian|http://www.radioswissclassic.ch/it/live/aacp32.m3u");
r->add("Radio Swiss Classic Italian|https://stream.srg-ssr.ch/rsc_it/aacp_96.m3u");
r->add("Radio Swiss Classic|http://stream.srg-ssr.ch/m/rsc_de/aacp_32");
r->add("Radio Swiss Classic|http://stream.srg-ssr.ch/m/rsc_de/aacp_96");
r->add("Radio Swiss Classic|http://stream.srg-ssr.ch/m/rsc_it/mp3_128");
r->add("Radio Swiss Classic|http://www.radioswissclassic.ch/de/live/aacp.m3u");
r->add("Radio Swiss Classic|https://stream.srg-ssr.ch/rsc_it/aacp_96.m3u");
r->add("Radio Swiss Classic|https://stream.srg-ssr.ch/rsc_it/aacp_96.m3u");
r->add("Radio Swiss Jazz|http://stream.srg-ssr.ch/m/rsj/aacp_32");
r->add("Radio Swiss Jazz|http://stream.srg-ssr.ch/m/rsj/aacp_96");
r->add("Radio Swiss Jazz|http://stream.srg-ssr.ch/m/rsj/aacp_96");
r->add("Radio Swiss Jazz|http://stream.srg-ssr.ch/m/rsj/mp3_128");
r->add("Radio Swiss Jazz|http://www.radioswissjazz.ch/live/aacp32.m3u");
r->add("Radio Swiss Jazz|https://stream.srg-ssr.ch/rsj/aacp_96.m3u");
r->add("Radio Swiss Jazz|https://stream.srg-ssr.ch/rsj/aacp_96.m3u");
r->add("Radio Swiss Pop|http://stream.srg-ssr.ch/m/rsp/aacp_32");
r->add("Radio Swiss Pop|http://stream.srg-ssr.ch/m/rsp/aacp_96");
r->add("Radio Swiss Pop|http://stream.srg-ssr.ch/m/rsp/mp3_128");
r->add("Radio Swiss Pop|http://www.radioswisspop.ch/live/aacp32.m3u");
r->add("Radio Swiss Pop|https://stream.srg-ssr.ch/rsp/aacp_96.m3u");
r->add("Radio Südostschweiz|http://streaming.swisstxt.ch/m/grischa/mp3_128");
r->add("Radio Tell|http://stream.radiotell.ch/radiotell.mp3");
r->add("Radio Top Two|http://77.109.144.109:8000/twosrp128");
r->add("Radio Top|http://77.109.144.109:8000/topsrp128");
r->add("Radio Vostok|http://radiovostok.ice.infomaniak.ch/radiovostok.aac");
r->add("Radio X Basel (MP3 Stream)|http://mp3.radiox.ch:8000/standard.mp3.m3u");
r->add("Radio X Basel (OGG Stream)|http://mp3.radiox.ch:8000/standard.ogg.m3u");
r->add("Radio Zürisee|http://mp3.radio.ch/radiozuerisee128k");
r->add("Radio grenzenlos|http://stream.grenzenlos.ch/");
r->add("Radio s|http://radio-s.feste-ip.net:8000/");
r->add("Radio-Drachenblut|https://radio-drachenblut.ch/stream.m3u");
r->add("Radio1.ch|https://stream.radio1.ch/128k");
r->add("Radio15.ch|http://radio15.ice.infomaniak.ch/radio15-192kbps.mp3?fbclid=IwAR1RgI4qFLCInWkcBZBlod__-7UXEufqWJJl2BnOT1s_xnkTuUQg8BG4avc");
r->add("Radio24|https://icecast.radio24.ch/radio24-rc-96-aac");
r->add("Radio3i|http://radio3i.ice.infomaniak.ch/radio3i-128.mp3");
r->add("Radio4TNG|http://radio4tng.ice.infomaniak.ch/radio4tng-live-web.mp3");
r->add("RadioFr. Freiburg|http://radiofreiburg.ice.infomaniak.ch/radiofreiburg-high.mp3");
r->add("RadioFr. Fribourg|http://radiofribourg.ice.infomaniak.ch/radiofribourg-high.mp3");
r->add("RadioPolis|http://rs01.swissnwx.ch:20080/stream");
r->add("Radionet+|http://radionetplus.ice.infomaniak.ch/radionetplus-high.mp3");
r->add("Radiopolis|http://rs01.swissnwx.ch:20080/stream");
r->add("Radioswiss |http://stream.laut.fm/radioswiss");
r->add("Rhône FM|http://rhonefm.ice.infomaniak.ch/rhonefm-high.aac");
r->add("Rhône FM|http://rhonefm.ice.infomaniak.ch/rhonefm-high.mp3");
r->add("Rock The Blues|http://stream.laut.fm/rock-the-blues");
r->add("Rouge FM 90s|http://rouge-90.ice.infomaniak.ch/rouge-90-128.mp3");
r->add("Rouge FM Latino|http://rouge-latino.ice.infomaniak.ch/rouge-latino-128.mp3");
r->add("Rouge FM Lounge|http://rougefm.ice.infomaniak.ch/rougefm-high.mp3");
r->add("Rouge FM Suisse|http://rouge-suisse.ice.infomaniak.ch/rouge-suisse-128.mp3");
r->add("Rouge Reggae|http://rouge-reggae.ice.infomaniak.ch/rouge-reggae-128.mp3");
r->add("Rundfunk.fm|http://rundfunk.ice.infomaniak.ch/rundfunk-192");
r->add("SRF 1|http://stream.srg-ssr.ch/m/drs1/mp3_128");
r->add("SRF 2|http://stream.srg-ssr.ch/drs2/mp3_128.m3u");
r->add("SRF 3|http://stream.srg-ssr.ch/m/drs3/mp3_128");
r->add("SRF 4 News|http://stream.srg-ssr.ch/m/drs4news/mp3_128");
r->add("SRF Musikwelle|http://stream.srg-ssr.ch/drsmw/mp3_128.m3u");
r->add("SRF Virus|http://stream.srg-ssr.ch/drsvirus/mp3_128.m3u");
r->add("SRF1 Radio|http://stream.srg-ssr.ch/drs1/aacp_96.m3u");
r->add("SRF1 Regionaljournal Aargau Solothurn|http://stream.srg-ssr.ch/regi_ag_so/aacp_96.m3u");
r->add("SWISS GROOVE|https://relay2.swissgroove.ch/;");
r->add("SWISSCLASSICA ITALIA|https://stream.srg-ssr.ch/rsc_it/mp3_128.m3u");
r->add("Skuizz Hits 90s-00s|https://traxx024.ice.infomaniak.ch/traxx024-1.mp3");
r->add("Spoon Radio - Acoustic Rock|https://spoonradioacousticrock.ice.infomaniak.ch/spoon-acousticrock-hd.aac");
r->add("Spoon Radio - Alternative Rock|https://spoonradioalternativerock.ice.infomaniak.ch/spoon-alternativerock-hd.aac");
r->add("Spoon Radio - Classic Rock|https://spoonradioclassicrock.ice.infomaniak.ch/spoon-classicrock-hd.aac");
r->add("Spoon Radio - Classic Rock|https://spoonradioclassicrock.ice.infomaniak.ch/spoon-classicrock-hd.aac");
r->add("Spoon Radio - Hard Rock|https://spoonradiohardrock.ice.infomaniak.ch/spoon-hardrock-hd.aac");
r->add("Spoon Radio - Modern Rock|https://spoonradiomodernrock.ice.infomaniak.ch/spoon-modernrock-hd.aac");
r->add("Spoon Radio - Rock Ballads|https://spoonradiorockballads.ice.infomaniak.ch/spoon-rockballads-hd.aac");
r->add("Spoon Radio|http://spoonradio.ice.infomaniak.ch/spoonradio-hd");
r->add("Spoon Radio|http://spoonradio.ice.infomaniak.ch/spoonradio-hd");
r->add("Spoon Radio|http://spoonradio.ice.infomaniak.ch/spoonradio-hd");
r->add("Sunradio - Best international Music|http://www.sunradio.ch/livestream.m3u");
r->add("Swiss Groove|https://relay1.swissgroove.ch/");
r->add("Swiss Melody|http://streams.rro.ch/swissmelody.mp3");
r->add("Swiss Pop|http://www.radioswisspop.ch/live/aacp.m3u");
r->add("SwissGroove|http://158.69.74.203/");
r->add("Swissradio.ch Classical|http://relay.publicdomainproject.org/classical.mp3");
r->add("Swissradio.ch Jazz & Swing|http://relay.publicdomainproject.org/jazz_swing.mp3");
r->add("Traxx FM - Ambient|http://traxx011.ice.infomaniak.ch/traxx011-low.mp3");
r->add("Traxx FM - Classic|http://traxx012.ice.infomaniak.ch/traxx012-low.mp3");
r->add("Traxx FM - Cool Jam|http://traxx005.ice.infomaniak.ch/traxx005-low.mp3");
r->add("Traxx FM - Deep|http://traxx013.ice.infomaniak.ch/traxx013-low.mp3");
r->add("Traxx FM - Deluxe|http://traxx001.ice.infomaniak.ch/traxx001-low.mp3");
r->add("Traxx FM - France|http://traxx025.ice.infomaniak.ch/traxx025-1.mp3");
r->add("Traxx FM - Funk|http://traxx016.ice.infomaniak.ch/traxx016-low.mp3");
r->add("Traxx FM - Golden Oldies|http://traxx023.ice.infomaniak.ch/traxx023-1.mp3");
r->add("Traxx FM - House|http://traxx002.ice.infomaniak.ch/traxx002-low.mp3");
r->add("Traxx FM - Italia|http://traxx021.ice.infomaniak.ch/traxx021-1.mp3");
r->add("Traxx FM - Jazz|http://traxx014.ice.infomaniak.ch/traxx014-low.mp3");
r->add("Traxx FM - Latino Pop|http://traxx022.ice.infomaniak.ch/traxx022-1.mp3");
r->add("Traxx FM - Latino|http://traxx008.ice.infomaniak.ch/traxx008-low.mp3");
r->add("Traxx FM - Lounge|http://traxx004.ice.infomaniak.ch/traxx004-low.mp3");
r->add("Traxx FM - Pop|http://traxx009.ice.infomaniak.ch/traxx009-low.mp3");
r->add("Traxx FM - Rap|http://traxx015.ice.infomaniak.ch/traxx015-low.mp3");
r->add("Traxx FM - RnB|http://traxx007.ice.infomaniak.ch/traxx007-low.mp3");
r->add("Traxx FM - Rock|http://traxx019.ice.infomaniak.ch/traxx019-low.mp3");
r->add("Traxx FM - Soul|http://traxx006.ice.infomaniak.ch/traxx006-low.mp3");
r->add("Traxx FM - Tech Minimal|http://traxx020.ice.infomaniak.ch/traxx020-low.mp3");
r->add("True House Chill|http://www.truehouse.net/chill.m3u");
r->add("True House Radio|http://www.truehouse.net/house.m3u");
r->add("UZIC.CH :: TECHNO - MINIMAL|http://stream.uzic.ch:9010/");
r->add("Varmusic|https://listen.radioking.com/radio/449177/stream/508205");
r->add("Vertical Radio|http://verticalradio.ice.infomaniak.ch/verticalradio-128.mp3");
r->add("Vibración Latina|http://vibration.stream2net.eu:8410/;stream/1");
r->add("Vibration 108|http://vibration108-high.ice.infomaniak.ch/vibration108-high.mp3");
r->add("Vibration Chanson Française|http://vibration.stream2net.eu:8510/;stream/1");
r->add("Vibration FM|http://vibration-aac.stream2net.eu:8040/listen.pls");
r->add("Vibration Gayradio|http://vibration.stream2net.eu:8480/;stream/1");
r->add("Vibration Poprock|http://vibrationpoprock.ice.infomaniak.ch/vibrationpoprock-high.mp3");
r->add("Vibration Poprock|http://vibrationpoprock.stream2net.eu:8030/listen.pls");
r->add("Vibration Soft Hits|http://vibration.stream2net.eu:8350/;stream/1");
r->add("Vibration Vintage|http://vibrationvintage-high.ice.infomaniak.ch/vibration-vintage.mp3");
r->add("Vibration Zen Relax|http://vibration.stream2net.eu:8220/;stream/1");
r->add("Vintage Radio|https://vintageradio.ice.infomaniak.ch/vintageradio-high.mp3");
r->add("Virgin Radio Switzerland Hits|http://icecast.argovia.ch/vhits");
r->add("Virgin Radio Switzerland Rock|http://icecast.argovia.ch/vrock");
r->add("World Radio Switzerland|https://uksouth.streaming.broadcast.radio:10290/wrs");
r->add("_ 101.4 YOUNG FM|https://canli.arabeskinmerkezi.com/9180/stream");
r->add("abc|https://lounge-radio.com/aacplus.m3u");
r->add("driftFM|https://s4.radio.co/s5729f2e59/listen");
r->add("electroradio.fm|http://n05.radiojar.com/fkyxx4q35k0uv");
r->add("ip music 320|http://live7.avf.ch:8000/ipmusic320");
r->add("lounge-radio.com|https://fr1.streamhosting.ch/lounge128.mp3");
r->add("my105 - All The Hits|http://stream01.my105.ch/my105allthehits.mp3");
r->add("my105 - Charts|http://stream01.my105.ch/my105charts.mp3");
r->add("my105 - Chill|http://stream01.my105.ch/my105chill.mp3");
r->add("my105 - DJ Mixes|http://stream01.my105.ch/my105djnights.mp3");
r->add("my105 - Dance|http://stream01.my105.ch/my105dance.mp3");
r->add("my105 - Deep|http://stream01.my105.ch/my105deep.mp3");
r->add("my105 - Deluxe|http://stream01.my105.ch/my105deluxe.mp3");
r->add("my105 - Dreist|http://stream01.my105.ch/my105dreist.mp3");
r->add("my105 - Fresh|http://stream01.my105.ch/my105fresh.mp3");
r->add("my105 - Love|http://stream01.my105.ch/my105love.mp3");
r->add("my105 - Mashup|http://stream01.my105.ch/my105mashup.mp3");
r->add("my105 - Original|http://stream01.my105.ch/my105original.mp3");
r->add("my105 - Party|http://stream01.my105.ch/my105party.mp3");
r->add("my105 - Ritmo Latino|http://stream01.my105.ch/my105ritmolatino.mp3");
r->add("my105 - Rock|http://stream01.my105.ch/my105rock.mp3");
r->add("my105 - The Battle|http://stream01.my105.ch/my105thebattle.mp3");
r->add("neo1|http://stream-02.neo1.ch/neo1");
r->add("radio vintage|http://statslive.infomaniak.ch/playlist/vintage/vintage.mp3/playlist.m3u");
r->add("rro - Müsig pur|http://streams.rro.ch/muesigpur.mp3");
r->add("rro - radio rotu oberwallis|http://streaming.swisstxt.ch/m/rro/mp3_128");
r->add("rro - wallisher geschichte|http://streams.rro.ch/event.mp3");
r->add("toxic.fm|http://toxicfm.ice.infomaniak.ch/toxicfm-128");

}

void Stations::add_slovenia(Fl_Browser *r)
{
r->add("Ars|http://mp3.rtvslo.si/ars");
r->add("Hit Radio Center (Ljubljana - 102.4MHz)|http://stream3.radiocenter.si:8000/;center/1");
r->add("Hitradio Center|http://stream3.radiocenter.si:8000/center");
r->add("Hitradio center 80's|http://stream3.radiocenter.si:8064/;stream/1");
r->add("Hitradio center fresh pop|http://stream3.radiocenter.si:8058/;stream/1");
r->add("Hitradio center latin|http://stream3.radiocenter.si:8200/;stream/1");
r->add("Hitradio center love|http://stream3.radiocenter.si:8060/;stream/1");
r->add("Hitradio center megamix|http://stream3.radiocenter.si:8066/;stream/1");
r->add("Hitradio center rock|http://stream.rockradio.si:9034/;stream/1");
r->add("Hitradio center top 100|http://stream3.radiocenter.si:9020/;stream/1");
r->add("Hitradio center yu|http://stream3.radiocenter.si:8100/;stream/1");
r->add("Muravidéki Magyar Rádió|http://mp3.rtvslo.si/mmr");
r->add("Primorski val|http://shoutcast.controlpanel.si:2199/tunein/primorskival-stream.pls");
r->add("RADIO CAPRIS XMAS|http://stream02.exit.si:8000/XMAS?");
r->add("ROCK RADIO SI|http://stream.rockradio.si:9034/;");
r->add("Radio 1 - Maribor (107.9MHz)|https://live.radio1.si/Radio1");
r->add("Radio 1|http://live.radio.si/Radio1");
r->add("Radio 2|http://live.radio2.si/Radio2?1448457274706.mo3");
r->add("Radio 2|http://live.radio2.si/Radio2?1448457274706.mp3");
r->add("Radio Aktual|http://195.95.158.131:9080/");
r->add("Radio Antena (105.2MHz)|https://live.radio.si/Antena");
r->add("Radio Antena|http://live.radioantena.si/Antena");
r->add("Radio BOB|http://live6.infonetmedia.si/Europa05");
r->add("Radio Capodistria|http://mp3.rtvslo.si/capo");
r->add("Radio Capris 80|http://stream02.exit.si:8000/80?");
r->add("Radio Capris 90 DANCE|http://stream02.exit.si:8000/MEGAMIX?");
r->add("Radio Capris 90 POP|http://stream02.exit.si:8000/90?");
r->add("Radio Capris Dalmacija|http://stream02.exit.si:8000/DALMACIJA?");
r->add("Radio Capris EX - YU|http://stream02.exit.si:8000/EXYU?");
r->add("Radio Capris Hits|http://stream02.exit.si:8000/HITS?");
r->add("Radio Capris ITALIA|http://stream02.exit.si:8000/ITA?");
r->add("Radio Capris LOVE|http://stream02.exit.si:8000/LOVE?");
r->add("Radio Capris POLETJE|http://stream02.exit.si:8000/POLETJE?");
r->add("Radio Capris Rock|http://stream02.exit.si:8000/ROCK?");
r->add("Radio Capris SLO|http://stream02.exit.si:8000/SLO?");
r->add("Radio Capris XMAS|https://stream.exit.si/XMAS");
r->add("Radio Celje|http://online-radio.eu/export/winamp/110935-radio-celje");
r->add("Radio City (Maribor) 100.6 FM|http://82.149.22.34:8000/CityMp364mono.mp3");
r->add("Radio City|https://stream1.radiocity.si/CityMp3128.mp3");
r->add("Radio Ekspres|http://93.103.13.156:8000/");
r->add("Radio Expres|http://stream2.radioekspres.si:8016/stream?type=http&nocache=138");
r->add("Radio Fantasy|http://146.247.24.74:8026/listen.pls?sid=1");
r->add("Radio Hit|http://stream03.exit.si:8000/radiohit");
r->add("Radio KRka|https://live.radio.si/Krka");
r->add("Radio Koper|http://mp3.rtvslo.si/rakp");
r->add("Radio MARŠ|http://frekvenca.eu:8000/radiomars.mp3.m3u");
r->add("Radio Maribor|https://mp3.rtvslo.si/rmb");
r->add("Radio Maxi|http://live2.infonetmedia.si:8000/Maxi");
r->add("Radio Meteor|http://eu1.fastcast4u.com:20052/stream");
r->add("Radio Murski Val|http://live.radio.si/murskival");
r->add("Radio Nula Beatz|https://strm.radionula.com/lounge");
r->add("Radio Nula Classics|http://streaming.radionula.com:8800/classics");
r->add("Radio Nula Classic|https://strm.radionula.com/classics");
r->add("Radio Nula Organic|https://strm.radionula.com/channel2");
r->add("Radio Nula|https://strm.radionula.com/classics");
r->add("Radio Ognjišče - mp3 stream|http://radio.ognjisce.si/ognjisce/iradio/ognjiscemp3.m3u");
r->add("Radio Prvi|http://mp3.rtvslo.si/ra1");
r->add("Radio Roška|http://stream.zeno.fm/q7300aptbwzuv");
r->add("Radio Salomon Back In Time|https://live.radio.si/SalomonBIT");
r->add("Radio Salomon|http://84.52.138.44/Salomon");
r->add("Radio Si|http://mp3.rtvslo.si/rsi");
r->add("Radio Sora|http://radio-sora.si:8000/radio-sora.mp3");
r->add("Radio Sraka|http://193.105.67.24:8006/");
r->add("Radio Terminal|https://air.radioterminal.si/live");
r->add("Radio Triglav|http://live.radiotriglav.si/Triglav");
r->add("Radio Velenje|http://212.18.39.42:8000/radiovelenje.mp3");
r->add("Radio Veseljak-Pumpa|http://live.radio.si/VeseljakPumpa");
r->add("Radio Veseljak|http://195.95.158.131:9060/");
r->add("Radio Zica|http://live.1chi.si/zica");
r->add("Radio Študent|http://kruljo.radiostudent.si:8000/hiq.m3u");
r->add("Radio Študent|http://kruljo.radiostudent.si:8000/loq.m3u");
r->add("Rock Maribor|http://live.rockmaribor.si/RockMB");
r->add("Rock Radio|http://stream3.radiocenter.si:9032/;");
r->add("Val 202|http://mp3.rtvslo.si/val202");
r->add("radio nula 2|http://streaming.radionula.com:8800/channel2");
r->add("radio nula lounge|http://streaming.radionula.com:8800/lounge");

}

void Stations::add_austria(Fl_Browser *r)
{
r->add("_01 SALZBURG FM|https://canli.arabeskinmerkezi.com/9180/stream");
r->add("ARBÖ Verkehrsradio|http://live.datamatix.at:8022/");
r->add("Antenna Österreich|https://frontend.streamonkey.net/antoesterreich-live");
r->add("Antenne Austro Hits|https://live.antenne.at/auh");
r->add("Antenne Kärnten Partyhitmix|http://live.antenne.at/ost");
r->add("Antenne Kärnten Sunrise|http://live.antenne.at/sun");
r->add("Antenne Kärnten|http://live.antenne.at/ak");
r->add("Antenne Steiermark|http://live.antenne.at/as");
r->add("Antenne Vorarlberg 2000er Hits|https://web.radio.antennevorarlberg.at/av-2000er");
r->add("Antenne Vorarlberg 2010er Hits|https://web.radio.antennevorarlberg.at/av-2010er");
r->add("Antenne Vorarlberg 70er Hits|https://web.radio.antennevorarlberg.at/av-70er");
r->add("Antenne Vorarlberg 90s Hits|https://web.radio.antennevorarlberg.at/av-90er");
r->add("Antenne Vorarlberg Chillout Lounge |https://web.radio.antennevorarlberg.at/av-chillout");
r->add("Antenne Vorarlberg Chillout Lounge |https://web.radio.antennevorarlberg.at/av-chillout");
r->add("Antenne Vorarlberg Chillout|https://web.radio.antennevorarlberg.at/av-chillout/stream/mp3");
r->add("Antenne Vorarlberg Christkindl Radio|https://web.radio.antennevorarlberg.at/av-christkindl");
r->add("Antenne Vorarlberg Classic Rock|https://web.radio.antennevorarlberg.at/av-classicrock/stream/mp3");
r->add("Antenne Vorarlberg Coffee Hits|https://web.radio.antennevorarlberg.at/av-coffee");
r->add("Antenne Vorarlberg Dance Radio|https://web.radio.antennevorarlberg.at/av-dance");
r->add("Antenne Vorarlberg Lovesongs|https://web.radio.antennevorarlberg.at/av-lovesongs/stream/mp3");
r->add("Antenne Vorarlberg Musica Italiana|https://web.radio.antennevorarlberg.at/av-italiana");
r->add("Antenne Vorarlberg Oldies but Goldies|https://web.radio.antennevorarlberg.at/av-oldies");
r->add("Antenne Vorarlberg PLUS 80er, 90er Hits|https://web.radio.antennevorarlberg.at/av-plus80er90er");
r->add("Antenne Vorarlberg PLUS Neue Hits|https://web.radio.antennevorarlberg.at/av-plusneuehits");
r->add("Antenne Vorarlberg Partymix|https://web.radio.antennevorarlberg.at/av-partymix");
r->add("Antenne Vorarlberg Rock Radio|https://web.radio.antennevorarlberg.at/av-rock");
r->add("Antenne Vorarlberg Schlagerkult|https://web.radio.antennevorarlberg.at/av-schlagerkult");
r->add("Antenne Vorarlberg TOP40|https://web.radio.antennevorarlberg.at/av-top40");
r->add("Antenne Vorarlberg|https://web.radio.antennevorarlberg.at/av-live?aggregator=Radioplayer");
r->add("Antenne vorarlberg Non Stop|https://web.radio.antennevorarlberg.at/av-nonstop");
r->add("Antenne Österreich|https://frontend.streamonkey.net/antoesterreich-live");
r->add("Arabella Austropop|https://static.arabella.at/streamadressen/arabella-austropop.m3u");
r->add("Arabella Relax|https://static.arabella.at/streamadressen/arabella-relax.m3u");
r->add("Atnnene sSterewich|https://frontend.streamonkey.net/antoesterreich-live");
r->add("Austria-Kult-Radio|http://stream.laut.fm/austria-kultradio.m3u");
r->add("AustriaKult-Radio|http://stream.laut.fm/austria-kultradio");
r->add("Austrian Rock Radio|http://live.antenne.at/arr");
r->add("AustrianPub-Radio|https://server7.streamserver24.com:8080/proxy/emburger?mp=/stream");
r->add("Blechradio 1|https://streamt.at/radio/8000/blechradio1.mp3");
r->add("CITY23|http://live.radiomax.technology/city23");
r->add("Chill Out Zone Plus - Lossless/FLAC|http://chillout.zone/chillout_plus");
r->add("Chill Out Zone|http://air.chillout.zone:8000/radio");
r->add("Chromatique-Sky|http://stream.laut.fm/chromatique-sky");
r->add("DJ2|https://www.djing.com/tv/s-28062-05-electro-rock.m3u8");
r->add("Darksynth Radio|http://stream.laut.fm/darksynthradio");
r->add("Dein Salzkammergutradio|http://rs2.myradio24.de:8410/stream");
r->add("DrumandBass.FM|http://stream.laut.fm/drumandbass_fm");
r->add("ERF Plus Oesterreich 192k|http://stream.erf.at/erfplus_192");
r->add("Energy-NRJ Innsbruck|http://stream1.energy.at:8000/ibk");
r->add("Energy-NRJ Wien|http://cdn.nrjaudio.fm/adwz1/at/36001/mp3_128.mp3");
r->add("FREIRAD|https://stream.freirad.at/live.ogg");
r->add("Freies Radio Freistadt|http://212.89.182.114:8008/frf");
r->add("Freies Radio Salzkammergut|http://stream.xaok.org:8000/frs.mp3");
r->add("Freies Radio Österreich|http://www.fro.at:8008/fro64.mp3");
r->add("Heiligenkreuz_101 (102k)|http://live.radiomaria.at:8000/rma101");
r->add("Heiligenkreuz_102 (166k)|http://live.radiomaria.at:8000/rma102");
r->add("I-love-Radio-104|https://streams.ilovemusic.de/iloveradio104.mp3");
r->add("JazzW3|https://air.jazz.w3.at/jazzw3.mp3");
r->add("JazzW3|https://air.jazz.w3.at/jazzw3.ogg");
r->add("Jugoton Hit Radio Wien|http://s8.iqstreaming.com:8060/;stream.nsv");
r->add("KroneHit - Hardstyle|https://secureonair.krone.at/kronehit16.mp3");
r->add("KroneHit Digital|http://onair-ha1.krone.at/kronehit1058.mp3");
r->add("KroneHit Radio|http://onair-ha1.krone.at/kronehit.aac");
r->add("KroneHit Radio|http://onair-ha1.krone.at/kronehit64.aac");
r->add("KroneHit Vollgas|https://secureonair.krone.at/kronehit11.mp3");
r->add("Kronehit AustroPOP|https://secureonair.krone.at/kronehit17.mp3");
r->add("Kronehit Disco|http://secureonair.krone.at/kronehit03.mp3");
r->add("Kronehit Greatesthits|https://secureonair.krone.at/kronehit13.mp3");
r->add("Kronehit Love|https://secureonair.krone.at/kronehit14.mp3");
r->add("Kronehit Season Event (SpringBreak / Summer / Halloween / Christmas)|https://secureonair.krone.at/kronehit12.mp3");
r->add("Kronehit|http://onair.krone.at/kronehit.mp3");
r->add("Life Radio 90er|http://stream3.liferadio.at/;");
r->add("Life Radio Chill Out|https://stream8.liferadio.at/");
r->add("Life Radio Classic Rock |https://stream11.liferadio.at/");
r->add("Life Radio ClassicRock|https://stream.liferadio.at/clrock/mp3-192/stream.liferadio.at/");
r->add("Life Radio Tirol|http://194.232.200.164:8000/;638826246082377stream.nsv");
r->add("Life Radio|http://stream1.liferadio.at/");
r->add("Live Radio Tirol|https://liferadiotirol.apa.at:8000/");
r->add("Lounge FM|https://digital.lounge.fm/");
r->add("Lounge.FM - 100% Austria|https://s35.derstream.net/100austria.mp3");
r->add("LoungeFM 100% Austria|http://188.138.9.183/100austria.mp3");
r->add("LoungeFM Digital|http://188.138.9.183/digital.mp3");
r->add("LoungeFM UKW Wien|http://188.138.9.183/lounge-at.mp3");
r->add("Moj Radio|http://www.mojradio.net/play/playlist.pls");
r->add("Mountain Reggae Radio|https://mountainreggaeradio.stream.laut.fm/mountainreggaeradio");
r->add("Museumsradio AM 1476|https://museum.streamserver24.com:8080/stream");
r->add("NJoy Radio 88.2 Steiermark|http://live.njoyradio.at/njoy");
r->add("NRJ.at - Hits|http://cdn.nrjaudio.fm/adwz1/at/36045/aac_64.mp3");
r->add("NRJ.at - Pop|http://cdn.nrjaudio.fm/adwz1/at/36063/aac_64.mp3");
r->add("Now Radio 192k|http://stream.erf.at/nowradio_192");
r->add("Now Radio 96k|http://stream.erf.at/nowradio_96");
r->add("ORF Hitradio Ö3|http://orf-live.ors-shoutcast.at/oe3-q1a");
r->add("ORF Radio Burgenland|https://orf-live-bgl.mdn.ors.at/out/u/bgl/q4a/manifest.m3u8?player=radiothek_v1");
r->add("ORF Radio Kärnten|http://ors-sn02.ors-shoutcast.at/ktn-q1a");
r->add("ORF Radio Kärnten|https://orf-live-ktn.mdn.ors.at/out/u/ktn/q4a/manifest.m3u8?player=radiothek_v1");
r->add("ORF Radio Oberösterreich|https://orf-live.ors-shoutcast.at/ooe-q2a.m3u");
r->add("ORF Radio Salzburg neu http|http://orf-live.ors-shoutcast.at/sbg-q2a");
r->add("ORF Radio Wien|http://orf-live.ors-shoutcast.at/wie-q2a.m3u");
r->add("ORF Tirol http1|http://orf-live.ors-shoutcast.at/tir-q1a");
r->add("ORF Tirol http|http://orf-live.ors-shoutcast.at/tir-q2a");
r->add("ORF Ö1 Campus|https://orf-live.ors-shoutcast.at/campus-q1a");
r->add("ORF Ö1 Campus|https://orf-live.ors-shoutcast.at/campus-q2a");
r->add("ORF Ö1|https://orf-live.ors-shoutcast.at/oe1-q1a");
r->add("ORF Ö1|https://orf-live.ors-shoutcast.at/oe1-q2a");
r->add("ORF.AT Schlagersterne|https://orf-live.ors-shoutcast.at/ktn-q2a?cb=1666746171587&player=sound_v1&referer=sound.orf.at&userid=399b1538-3aa9-4bf9-93fc-766dd33f1a1e");
r->add("ORF: Radio Salzburg|https://orf-live-sbg.mdn.ors.at/out/u/sbg/q4a/manifest.m3u8");
r->add("ORF: Radio Salzburg|https://orf-live-sbg.mdn.ors.at/out/u/sbg/q4a/manifest.m3u8?player=radiothek_v1");
r->add("ORF: Ö1 DD|https://oe1dd.mdn.ors.at/out/u/oe1dd/manifest.m3u8");
r->add("Oldie Party|http://streams.norawebstreams.de/oldieparty/mp3-192/vtuner/");
r->add("Orange 94.0 secure|https://securestream.o94.at/live.mp3");
r->add("PetersPlattentek|https://server7524.streamplus.de/stream.mp3");
r->add("RES.RADIO|https://edge.mixlr.com/channel/zwtuo");
r->add("Radino - Mein Kinderradio Wien 103,2|http://stream01.zogl.net:8906/stream");
r->add("Radio 88,6 Classic Rock|http://radio886.at/streams/88.6_Classic_Rock/mp3");
r->add("Radio 88.6 Hard Rock|https://edge51.streamonkey.net/radio886-hardrock/stream/mp3?aggregator=886Website");
r->add("Radio 88.6 New Rock|https://edge51.streamonkey.net/radio886-newrock/stream/mp3?aggregator=886Website");
r->add("Radio 88.6 Rot-Weiß-Rock|https://edge06.streamonkey.net/radio886-rotweissrock/stream/mp3?aggregator=886Website");
r->add("Radio Alpenstar|http://streamplus62.leonex.de:22674/;");
r->add("Radio Arabella Oberösterreich|https://frontend.streams.arabella.at/arabella-oberoesterreich?aggregator=tunein");
r->add("Radio Austria|https://onair.securestream.radioaustria.at/radioaustria");
r->add("Radio B138|http://radiob138.out.airtime.pro:8000/radiob138_a");
r->add("Radio Burgenland neu|http://orf-live.ors-shoutcast.at/bgl-q2a");
r->add("Radio ECHOPLUS|http://radio2.stream24.net:9120/live.mp3");
r->add("Radio FM4|http://orf-live.ors-shoutcast.at/fm4-q2a");
r->add("Radio FRO|http://www.fro.at:8008/fro-128.ogg");
r->add("Radio Flamingo|http://live.antenne.at/rf");
r->add("Radio Freequenns|http://livestream.freequenns.at/live");
r->add("Radio Grün Weiß - HQ|http://live.gruen-weiss.at/rgw.aac");
r->add("Radio Grün Weiß|http://live.gruen-weiss.at/rgw.mp3");
r->add("Radio Harmonie|http://host6.cartwall.at:9630/");
r->add("Radio Helsinki 92,6 MHz (128 kbps)|http://live.helsinki.at:8088/live128.mp3");
r->add("Radio Helsinki 92,6 MHz (160 kbps)|http://live.helsinki.at:8088/live160.mp3");
r->add("Radio Himmelberg|http://stream.laut.fm/radio-himmelberg");
r->add("Radio Klassik Stephansdom|http://radioklassikstephansdom.ice.infomaniak.ch/radioklassikstephansdom.mp3");
r->add("Radio Kärnten neu|http://orf-live.ors-shoutcast.at/ktn-q2a");
r->add("Radio Liria|http://46.4.104.253:9998/;");
r->add("Radio Maria Austria (56 kbps)|http://live.radiomaria.at:8000/rma2");
r->add("Radio Maria Austria|http://live.radiomaria.at:8000/rma.m3u");
r->add("Radio Max Billa|http://listen.radiomax.technology/billa");
r->add("Radio Max Bipa|http://listen.radiomax.technology/bipa");
r->add("Radio Max Merkur|http://listen.radiomax.technology/merkur");
r->add("Radio Max Penny|http://listen.radiomax.technology/penny");
r->add("Radio NJOY Wien|http://94.136.28.9:8005/njoyradio-hd");
r->add("Radio Niederösterreich neu|http://orf-live.ors-shoutcast.at/noe-q2a");
r->add("Radio OE1 neu|http://orf-live.ors-shoutcast.at/oe1-q2a");
r->add("Radio OE3 neu|http://orf-live.ors-shoutcast.at/oe3-q2a");
r->add("Radio OP|https://server4.streamserver24.com:26250/stream");
r->add("Radio Oberösterreich neu|http://orf-live.ors-shoutcast.at/ooe-q2a");
r->add("Radio Osttirol|http://streamplus20.leonex.de:28768/;");
r->add("Radio Seniorkom|http://93.185.134.22:8080/seniorkom");
r->add("Radio Steiermark 80er POP|https://live.antenne.at/80s");
r->add("Radio Steiermark neu|http://orf-live.ors-shoutcast.at/stm-q2a");
r->add("Radio Studio Enns|https://server4.streamserver24.com:61414/");
r->add("Radio U1 Tirol|https://live.u1-radio.at/");
r->add("Radio Val Canale|https://server1.cityedv.at:2199/tunein/radcanale_ic.pls");
r->add("Radio ViennaPLus Polskie Radio Wieden|http://radio.viennaplus.at:8000/");
r->add("Radio Vorarlberg neu|http://orf-live.ors-shoutcast.at/vbg-q2a");
r->add("Radio Vorarlberg|https://orf-live.ors-shoutcast.at/vbg-q1a");
r->add("Radio Vorarlberg|https://orf-live.ors-shoutcast.at/vbg-q2a");
r->add("Radio Wien neu|http://orf-live.ors-shoutcast.at/wie-q2a");
r->add("Radio Xmas|http://www.radio-xmas.at:443/xmas?1512905036085");
r->add("Radio Ö24|http://streamplus14.leonex.de:24954/");
r->add("Radio Ö24|http://streamplus14.leonex.de:24954/listen.pls");
r->add("Radiofabrik|https://radiofabrik.at/rafab_stream_low.m3u");
r->add("Radyo Maximum|http://ip169.ozelip.com:9970/");
r->add("Radyo Maximum|http://ip169.ozelip.com:9970/stream?type=http&nocache=5");
r->add("Radyo Maximum|http://radyomaximum.kesintisizyayin.com:9970/");
r->add("Radyo Maximum|http://radyomaximum.kesintisizyayin.com:9970/");
r->add("Rock Antenne Österreich|http://mp3channels.webradio.de/rockantenne-oesterreich");
r->add("Schwendermarkt|https://laut.fm/schwendermarkt");
r->add("Soundportal (MP3, 128 kBit)|http://rs8.stream24.net/radio-soundportal.mp3");
r->add("Spirit Live Radio|http://server7606.streamplus.de/;");
r->add("Stadtradio Krems|http://musikwelle.com:8000/stream.mp3");
r->add("Stahlradio|https://simba.streampanel.cloud:5280/stream");
r->add("Styrialounge|http://styrialounge.out.airtime.pro:8000/styrialounge_a");
r->add("Styrialounge|https://styrialounge.out.airtime.pro/styrialounge_a");
r->add("Superfly FM|http://stream01.superfly.fm:8080/live128");
r->add("Technikum CITY|http://technikumsmoothjazz.macjingle.at:8206/;stream/1");
r->add("Technikum City|https://stream.radiotechnikum.at/TECHCITY");
r->add("Technikum Gold|https://stream.radiotechnikum.at/TECHGOLD");
r->add("Technikum ONE|http://radiotechnikum.macjingle.at:8200/;stream/1");
r->add("Technikum One|https://stream.radiotechnikum.at/TECHONE");
r->add("Technikum Rock|https://stream.radiotechnikum.at/TECHROCK");
r->add("Toilette Live|http://n12.radiojar.com/ya73ubvq6yzuv");
r->add("Viyana FM|https://radyo.viyanafm.at/1453/stream");
r->add("ViyanaFM|https://radyo.viyanafm.at/1453/stream");
r->add("WELLE 1 music radio DAB+ Österreich PREMIUM 256k stereo|https://live.welle1.at:19000/stream");
r->add("WELLE 1 music radio Oberöstereich 91,8 128k stereo|https://live.welle1.at:17128/stream");
r->add("WELLE 1 music radio Oberösterreich 91,8 PREMIUM 256k stereo|https://live.welle1.at:17256/stream");
r->add("Welle 1 - Kärnten, 128k|https://live.welle1.at:15128/stream");
r->add("Welle 1 - Kärnten, 256k|https://live.welle1.at:15256/stream");
r->add("Welle 1 - Wien/DAB+|https://live.welle1.at:19000/stream");
r->add("Welle 1 Salzburg|https://live.welle1.at:18256/stream");
r->add("Welle1|https://live.welle1.at:17128/stream");
r->add("Yeshua.at Radio|https://yeshua.at:8443/stream");
r->add("antennevorarlberg coffee|http://web.radio.antennevorarlberg.at/av-coffee/stream/mp3?aggregator=icecastdirectory");
r->add("mala-tunes|http://stream.laut.fm/mala-tunes");
r->add("mumiix fas|http://radyomaximum.kesintisizyayin.com:9970/");
r->add("oe1 surround |https://oe1dd.mdn.ors.at/out/u/oe1dd/manifest.m3u8");
r->add("oe3|https://orf-live.ors-shoutcast.at/oe3-q1a.m3u");
r->add("radio 88.6|http://radio886.at/streams/radio_88.6/mp3");
r->add("radio FM4 (192 kbps)|https://orf-live.ors-shoutcast.at/fm4-q2a");

}


void Stations::add_all(Fl_Browser *r)
{
add_serbia(r);
add_bosnia(r);
add_croatia(r);
add_switzerland(r);
add_slovenia(r);
add_austria(r);
}

/*void Stations::add_*(Fl_Browser *r)
{
}*/
