name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libfltk1.3-dev libxcursor-dev libxinerama-dev libxft-dev libfuse-dev
    - name: Compile
      run: make appimage
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: flradio-appimage
        path: FLRadio-x86_64.AppImage
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        tag_name: "${{ env.ver }}"
        release_name: "${{ env.ver }}"
      env:
        GITHUB_TOKEN: ${{ github.token }}
