name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: flradio
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libfltk1.3-dev libxcursor-dev libxinerama-dev libxft-dev libfuse-dev
    - name: Compile
      run: make appimage
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: flradio-appimage
        path: FLRadio-x86_64.AppImage
    - name: Upload linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./FLRadio-x86_64.AppImage
        asset_name: FLRadio-x86_64.AppImage
        asset_content_type: application/x-iso9660-appimage
