name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libfltk1.3-dev libxcursor-dev libxinerama-dev libxft-dev libfuse-dev
    - name: Compile
      run: make appimage
    - name: Create release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        tag_name: "flradio-${{ github.run_number }}"
        release_name: "flradio-${{ github.run_number }}"
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Export upload URL
      run: echo "UPLOAD_URL=${{ steps.create_release.outputs.upload_url }}" >> $GITHUB_ENV
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ env.UPLOAD_URL }}
        asset_path: ./FLRadio-x86_64.AppImage
        asset_name: FLRadio-x86_64.AppImage
        asset_content_type: application/x-iso9660-appimage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
